android.useAndroidX=true

# @BindView requires a constant resource ID
android.nonFinalResIds=false

Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

org.gradle.jvmargs=-Dhttps.protocols=TLSv1.2,TLSv1.3

systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3

# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=8118
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=8118

# systemProp.socksProxyHost = 127.0.0.1
# systemProp.socksProxyPort = 9090
