// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cameraqueryeventmessage.proto

package com.huiti.clipcms;

import android.net.Uri;
import android.webkit.WebView;

public interface SbWebViewClientInterface
{
  void onFoundVideoUrl(Uri uri, WebView webView); //!<报告，找到了视频网址。
  void onPageFinished(WebView view, String url); //!<由活动来处理。网页载入完毕。
}
