// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccurateVoiceCommandListMessage.proto

package com.stupidbeauty.hxlauncher;

public interface AccurateVoiceCommandListMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.AccurateVoiceCommandListMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *语音指令列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.VoiceCommandMessage voiceCommandList = 1;</code>
   */
  java.util.List<com.stupidbeauty.hxlauncher.VoiceCommandMessage> 
      getVoiceCommandListList();
  /**
   * <pre>
   *语音指令列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.VoiceCommandMessage voiceCommandList = 1;</code>
   */
  com.stupidbeauty.hxlauncher.VoiceCommandMessage getVoiceCommandList(int index);
  /**
   * <pre>
   *语音指令列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.VoiceCommandMessage voiceCommandList = 1;</code>
   */
  int getVoiceCommandListCount();
  /**
   * <pre>
   *语音指令列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.VoiceCommandMessage voiceCommandList = 1;</code>
   */
  java.util.List<? extends com.stupidbeauty.hxlauncher.VoiceCommandMessageOrBuilder> 
      getVoiceCommandListOrBuilderList();
  /**
   * <pre>
   *语音指令列表。
   * </pre>
   *
   * <code>repeated .com.stupidbeauty.hxlauncher.VoiceCommandMessage voiceCommandList = 1;</code>
   */
  com.stupidbeauty.hxlauncher.VoiceCommandMessageOrBuilder getVoiceCommandListOrBuilder(
      int index);

  /**
   * <pre>
   *     DummyReq stopVoiceRecognizeMessage=2; //停止语音识别消息体。已废弃。
   *     VoiceRecognizeReq startVoiceRecognizeMessage=3; //开始语音识别消息体。已废弃。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
   */
  boolean hasSetLanguageMessage();
  /**
   * <pre>
   *     DummyReq stopVoiceRecognizeMessage=2; //停止语音识别消息体。已废弃。
   *     VoiceRecognizeReq startVoiceRecognizeMessage=3; //开始语音识别消息体。已废弃。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
   */
  com.stupidbeauty.hxlauncher.SetLanguageReq getSetLanguageMessage();
  /**
   * <pre>
   *     DummyReq stopVoiceRecognizeMessage=2; //停止语音识别消息体。已废弃。
   *     VoiceRecognizeReq startVoiceRecognizeMessage=3; //开始语音识别消息体。已废弃。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
   */
  com.stupidbeauty.hxlauncher.SetLanguageReqOrBuilder getSetLanguageMessageOrBuilder();

  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  boolean hasReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage();
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder();

  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  boolean hasSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq getSet3DEngineCameraPositionRotationMessage();
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder getSet3DEngineCameraPositionRotationMessageOrBuilder();
}
