// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccurateVoiceCommandReq.proto

package com.stupidbeauty.hxlauncher;

public final class AccurateVoiceCommandReqProtos {
  private AccurateVoiceCommandReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_AccurateVoiceCommandReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_AccurateVoiceCommandReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035AccurateVoiceCommandReq.proto\022\033com.stu" +
      "pidbeauty.hxlauncher\"=\n\027AccurateVoiceCom" +
      "mandReq\022\014\n\004text\030\001 \001(\t\022\024\n\014voiceCommand\030\002 " +
      "\001(\005B>\n\033com.stupidbeauty.hxlauncherB\035Accu" +
      "rateVoiceCommandReqProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_AccurateVoiceCommandReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_AccurateVoiceCommandReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_AccurateVoiceCommandReq_descriptor,
        new java.lang.String[] { "Text", "VoiceCommand", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
