// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AndroidApplicationMessage.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.AndroidApplicationMessage}
 */
public  final class AndroidApplicationMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.AndroidApplicationMessage)
    AndroidApplicationMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AndroidApplicationMessage.newBuilder() to construct.
  private AndroidApplicationMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AndroidApplicationMessage() {
    packageName_ = "";
    className_ = "";
    componentType_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AndroidApplicationMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            packageName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            className_ = s;
            break;
          }
          case 24: {
            int rawValue = input.readEnum();

            componentType_ = rawValue;
            break;
          }
          case 34: {
            com.stupidbeauty.hxlauncher.SetLanguageReq.Builder subBuilder = null;
            if (setLanguageMessage_ != null) {
              subBuilder = setLanguageMessage_.toBuilder();
            }
            setLanguageMessage_ = input.readMessage(com.stupidbeauty.hxlauncher.SetLanguageReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(setLanguageMessage_);
              setLanguageMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.Builder subBuilder = null;
            if (reportAudioSoundSourceReqMessage_ != null) {
              subBuilder = reportAudioSoundSourceReqMessage_.toBuilder();
            }
            reportAudioSoundSourceReqMessage_ = input.readMessage(com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reportAudioSoundSourceReqMessage_);
              reportAudioSoundSourceReqMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.Builder subBuilder = null;
            if (set3DEngineCameraPositionRotationMessage_ != null) {
              subBuilder = set3DEngineCameraPositionRotationMessage_.toBuilder();
            }
            set3DEngineCameraPositionRotationMessage_ = input.readMessage(com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(set3DEngineCameraPositionRotationMessage_);
              set3DEngineCameraPositionRotationMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.AndroidApplicationMessage.class, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType}
   */
  public enum ComponentType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *活动。
     * </pre>
     *
     * <code>ACTIVITY = 0;</code>
     */
    ACTIVITY(0),
    /**
     * <pre>
     *服务。
     * </pre>
     *
     * <code>SERVICE = 1;</code>
     */
    SERVICE(1),
    /**
     * <pre>
     *!&lt;不应当启动。
     * </pre>
     *
     * <code>NoLaunch = 2;</code>
     */
    NoLaunch(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *活动。
     * </pre>
     *
     * <code>ACTIVITY = 0;</code>
     */
    public static final int ACTIVITY_VALUE = 0;
    /**
     * <pre>
     *服务。
     * </pre>
     *
     * <code>SERVICE = 1;</code>
     */
    public static final int SERVICE_VALUE = 1;
    /**
     * <pre>
     *!&lt;不应当启动。
     * </pre>
     *
     * <code>NoLaunch = 2;</code>
     */
    public static final int NoLaunch_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ComponentType valueOf(int value) {
      return forNumber(value);
    }

    public static ComponentType forNumber(int value) {
      switch (value) {
        case 0: return ACTIVITY;
        case 1: return SERVICE;
        case 2: return NoLaunch;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ComponentType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ComponentType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ComponentType>() {
            public ComponentType findValueByNumber(int number) {
              return ComponentType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.AndroidApplicationMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final ComponentType[] VALUES = values();

    public static ComponentType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ComponentType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType)
  }

  public static final int PACKAGENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object packageName_;
  /**
   * <pre>
   *包名字。
   * </pre>
   *
   * <code>string packageName = 1;</code>
   */
  public java.lang.String getPackageName() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      packageName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *包名字。
   * </pre>
   *
   * <code>string packageName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getPackageNameBytes() {
    java.lang.Object ref = packageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      packageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CLASSNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object className_;
  /**
   * <pre>
   *类名字。可能是活动名字，也可能是服务名字。
   * </pre>
   *
   * <code>string className = 2;</code>
   */
  public java.lang.String getClassName() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      className_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *类名字。可能是活动名字，也可能是服务名字。
   * </pre>
   *
   * <code>string className = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClassNameBytes() {
    java.lang.Object ref = className_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      className_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPONENTTYPE_FIELD_NUMBER = 3;
  private int componentType_;
  /**
   * <pre>
   *组件类型。活动或服务。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
   */
  public int getComponentTypeValue() {
    return componentType_;
  }
  /**
   * <pre>
   *组件类型。活动或服务。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
   */
  public com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType getComponentType() {
    @SuppressWarnings("deprecation")
    com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType result = com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType.valueOf(componentType_);
    return result == null ? com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType.UNRECOGNIZED : result;
  }

  public static final int SETLANGUAGEMESSAGE_FIELD_NUMBER = 4;
  private com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage_;
  /**
   * <pre>
   *设置工作语言的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
   */
  public boolean hasSetLanguageMessage() {
    return setLanguageMessage_ != null;
  }
  /**
   * <pre>
   *设置工作语言的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
   */
  public com.stupidbeauty.hxlauncher.SetLanguageReq getSetLanguageMessage() {
    return setLanguageMessage_ == null ? com.stupidbeauty.hxlauncher.SetLanguageReq.getDefaultInstance() : setLanguageMessage_;
  }
  /**
   * <pre>
   *设置工作语言的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
   */
  public com.stupidbeauty.hxlauncher.SetLanguageReqOrBuilder getSetLanguageMessageOrBuilder() {
    return getSetLanguageMessage();
  }

  public static final int REPORTAUDIOSOUNDSOURCEREQMESSAGE_FIELD_NUMBER = 6;
  private com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage_;
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  public boolean hasReportAudioSoundSourceReqMessage() {
    return reportAudioSoundSourceReqMessage_ != null;
  }
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  public com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage() {
    return reportAudioSoundSourceReqMessage_ == null ? com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.getDefaultInstance() : reportAudioSoundSourceReqMessage_;
  }
  /**
   * <pre>
   *报告语音输入设备源的消息体。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
   */
  public com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder() {
    return getReportAudioSoundSourceReqMessage();
  }

  public static final int SET3DENGINECAMERAPOSITIONROTATIONMESSAGE_FIELD_NUMBER = 8;
  private com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage_;
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  public boolean hasSet3DEngineCameraPositionRotationMessage() {
    return set3DEngineCameraPositionRotationMessage_ != null;
  }
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  public com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq getSet3DEngineCameraPositionRotationMessage() {
    return set3DEngineCameraPositionRotationMessage_ == null ? com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.getDefaultInstance() : set3DEngineCameraPositionRotationMessage_;
  }
  /**
   * <pre>
   *设置三维人像的渲染相机位置及角度。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
   */
  public com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder getSet3DEngineCameraPositionRotationMessageOrBuilder() {
    return getSet3DEngineCameraPositionRotationMessage();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getPackageNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, packageName_);
    }
    if (!getClassNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, className_);
    }
    if (componentType_ != com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType.ACTIVITY.getNumber()) {
      output.writeEnum(3, componentType_);
    }
    if (setLanguageMessage_ != null) {
      output.writeMessage(4, getSetLanguageMessage());
    }
    if (reportAudioSoundSourceReqMessage_ != null) {
      output.writeMessage(6, getReportAudioSoundSourceReqMessage());
    }
    if (set3DEngineCameraPositionRotationMessage_ != null) {
      output.writeMessage(8, getSet3DEngineCameraPositionRotationMessage());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getPackageNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, packageName_);
    }
    if (!getClassNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, className_);
    }
    if (componentType_ != com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType.ACTIVITY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(3, componentType_);
    }
    if (setLanguageMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getSetLanguageMessage());
    }
    if (reportAudioSoundSourceReqMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getReportAudioSoundSourceReqMessage());
    }
    if (set3DEngineCameraPositionRotationMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getSet3DEngineCameraPositionRotationMessage());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.AndroidApplicationMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.AndroidApplicationMessage other = (com.stupidbeauty.hxlauncher.AndroidApplicationMessage) obj;

    boolean result = true;
    result = result && getPackageName()
        .equals(other.getPackageName());
    result = result && getClassName()
        .equals(other.getClassName());
    result = result && componentType_ == other.componentType_;
    result = result && (hasSetLanguageMessage() == other.hasSetLanguageMessage());
    if (hasSetLanguageMessage()) {
      result = result && getSetLanguageMessage()
          .equals(other.getSetLanguageMessage());
    }
    result = result && (hasReportAudioSoundSourceReqMessage() == other.hasReportAudioSoundSourceReqMessage());
    if (hasReportAudioSoundSourceReqMessage()) {
      result = result && getReportAudioSoundSourceReqMessage()
          .equals(other.getReportAudioSoundSourceReqMessage());
    }
    result = result && (hasSet3DEngineCameraPositionRotationMessage() == other.hasSet3DEngineCameraPositionRotationMessage());
    if (hasSet3DEngineCameraPositionRotationMessage()) {
      result = result && getSet3DEngineCameraPositionRotationMessage()
          .equals(other.getSet3DEngineCameraPositionRotationMessage());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PACKAGENAME_FIELD_NUMBER;
    hash = (53 * hash) + getPackageName().hashCode();
    hash = (37 * hash) + CLASSNAME_FIELD_NUMBER;
    hash = (53 * hash) + getClassName().hashCode();
    hash = (37 * hash) + COMPONENTTYPE_FIELD_NUMBER;
    hash = (53 * hash) + componentType_;
    if (hasSetLanguageMessage()) {
      hash = (37 * hash) + SETLANGUAGEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getSetLanguageMessage().hashCode();
    }
    if (hasReportAudioSoundSourceReqMessage()) {
      hash = (37 * hash) + REPORTAUDIOSOUNDSOURCEREQMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getReportAudioSoundSourceReqMessage().hashCode();
    }
    if (hasSet3DEngineCameraPositionRotationMessage()) {
      hash = (37 * hash) + SET3DENGINECAMERAPOSITIONROTATIONMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getSet3DEngineCameraPositionRotationMessage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.AndroidApplicationMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.AndroidApplicationMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.AndroidApplicationMessage)
      com.stupidbeauty.hxlauncher.AndroidApplicationMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.AndroidApplicationMessage.class, com.stupidbeauty.hxlauncher.AndroidApplicationMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.AndroidApplicationMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      packageName_ = "";

      className_ = "";

      componentType_ = 0;

      if (setLanguageMessageBuilder_ == null) {
        setLanguageMessage_ = null;
      } else {
        setLanguageMessage_ = null;
        setLanguageMessageBuilder_ = null;
      }
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        reportAudioSoundSourceReqMessage_ = null;
      } else {
        reportAudioSoundSourceReqMessage_ = null;
        reportAudioSoundSourceReqMessageBuilder_ = null;
      }
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        set3DEngineCameraPositionRotationMessage_ = null;
      } else {
        set3DEngineCameraPositionRotationMessage_ = null;
        set3DEngineCameraPositionRotationMessageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.AndroidApplicationMessageProtos.internal_static_com_stupidbeauty_hxlauncher_AndroidApplicationMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.AndroidApplicationMessage getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.AndroidApplicationMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.AndroidApplicationMessage build() {
      com.stupidbeauty.hxlauncher.AndroidApplicationMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.AndroidApplicationMessage buildPartial() {
      com.stupidbeauty.hxlauncher.AndroidApplicationMessage result = new com.stupidbeauty.hxlauncher.AndroidApplicationMessage(this);
      result.packageName_ = packageName_;
      result.className_ = className_;
      result.componentType_ = componentType_;
      if (setLanguageMessageBuilder_ == null) {
        result.setLanguageMessage_ = setLanguageMessage_;
      } else {
        result.setLanguageMessage_ = setLanguageMessageBuilder_.build();
      }
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        result.reportAudioSoundSourceReqMessage_ = reportAudioSoundSourceReqMessage_;
      } else {
        result.reportAudioSoundSourceReqMessage_ = reportAudioSoundSourceReqMessageBuilder_.build();
      }
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        result.set3DEngineCameraPositionRotationMessage_ = set3DEngineCameraPositionRotationMessage_;
      } else {
        result.set3DEngineCameraPositionRotationMessage_ = set3DEngineCameraPositionRotationMessageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.AndroidApplicationMessage) {
        return mergeFrom((com.stupidbeauty.hxlauncher.AndroidApplicationMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.AndroidApplicationMessage other) {
      if (other == com.stupidbeauty.hxlauncher.AndroidApplicationMessage.getDefaultInstance()) return this;
      if (!other.getPackageName().isEmpty()) {
        packageName_ = other.packageName_;
        onChanged();
      }
      if (!other.getClassName().isEmpty()) {
        className_ = other.className_;
        onChanged();
      }
      if (other.componentType_ != 0) {
        setComponentTypeValue(other.getComponentTypeValue());
      }
      if (other.hasSetLanguageMessage()) {
        mergeSetLanguageMessage(other.getSetLanguageMessage());
      }
      if (other.hasReportAudioSoundSourceReqMessage()) {
        mergeReportAudioSoundSourceReqMessage(other.getReportAudioSoundSourceReqMessage());
      }
      if (other.hasSet3DEngineCameraPositionRotationMessage()) {
        mergeSet3DEngineCameraPositionRotationMessage(other.getSet3DEngineCameraPositionRotationMessage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.AndroidApplicationMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.AndroidApplicationMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object packageName_ = "";
    /**
     * <pre>
     *包名字。
     * </pre>
     *
     * <code>string packageName = 1;</code>
     */
    public java.lang.String getPackageName() {
      java.lang.Object ref = packageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *包名字。
     * </pre>
     *
     * <code>string packageName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPackageNameBytes() {
      java.lang.Object ref = packageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *包名字。
     * </pre>
     *
     * <code>string packageName = 1;</code>
     */
    public Builder setPackageName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      packageName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *包名字。
     * </pre>
     *
     * <code>string packageName = 1;</code>
     */
    public Builder clearPackageName() {
      
      packageName_ = getDefaultInstance().getPackageName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *包名字。
     * </pre>
     *
     * <code>string packageName = 1;</code>
     */
    public Builder setPackageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      packageName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object className_ = "";
    /**
     * <pre>
     *类名字。可能是活动名字，也可能是服务名字。
     * </pre>
     *
     * <code>string className = 2;</code>
     */
    public java.lang.String getClassName() {
      java.lang.Object ref = className_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        className_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *类名字。可能是活动名字，也可能是服务名字。
     * </pre>
     *
     * <code>string className = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClassNameBytes() {
      java.lang.Object ref = className_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        className_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *类名字。可能是活动名字，也可能是服务名字。
     * </pre>
     *
     * <code>string className = 2;</code>
     */
    public Builder setClassName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      className_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *类名字。可能是活动名字，也可能是服务名字。
     * </pre>
     *
     * <code>string className = 2;</code>
     */
    public Builder clearClassName() {
      
      className_ = getDefaultInstance().getClassName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *类名字。可能是活动名字，也可能是服务名字。
     * </pre>
     *
     * <code>string className = 2;</code>
     */
    public Builder setClassNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      className_ = value;
      onChanged();
      return this;
    }

    private int componentType_ = 0;
    /**
     * <pre>
     *组件类型。活动或服务。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
     */
    public int getComponentTypeValue() {
      return componentType_;
    }
    /**
     * <pre>
     *组件类型。活动或服务。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
     */
    public Builder setComponentTypeValue(int value) {
      componentType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组件类型。活动或服务。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
     */
    public com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType getComponentType() {
      @SuppressWarnings("deprecation")
      com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType result = com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType.valueOf(componentType_);
      return result == null ? com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     *组件类型。活动或服务。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
     */
    public Builder setComponentType(com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      componentType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *组件类型。活动或服务。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AndroidApplicationMessage.ComponentType componentType = 3;</code>
     */
    public Builder clearComponentType() {
      
      componentType_ = 0;
      onChanged();
      return this;
    }

    private com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.SetLanguageReq, com.stupidbeauty.hxlauncher.SetLanguageReq.Builder, com.stupidbeauty.hxlauncher.SetLanguageReqOrBuilder> setLanguageMessageBuilder_;
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public boolean hasSetLanguageMessage() {
      return setLanguageMessageBuilder_ != null || setLanguageMessage_ != null;
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public com.stupidbeauty.hxlauncher.SetLanguageReq getSetLanguageMessage() {
      if (setLanguageMessageBuilder_ == null) {
        return setLanguageMessage_ == null ? com.stupidbeauty.hxlauncher.SetLanguageReq.getDefaultInstance() : setLanguageMessage_;
      } else {
        return setLanguageMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public Builder setSetLanguageMessage(com.stupidbeauty.hxlauncher.SetLanguageReq value) {
      if (setLanguageMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        setLanguageMessage_ = value;
        onChanged();
      } else {
        setLanguageMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public Builder setSetLanguageMessage(
        com.stupidbeauty.hxlauncher.SetLanguageReq.Builder builderForValue) {
      if (setLanguageMessageBuilder_ == null) {
        setLanguageMessage_ = builderForValue.build();
        onChanged();
      } else {
        setLanguageMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public Builder mergeSetLanguageMessage(com.stupidbeauty.hxlauncher.SetLanguageReq value) {
      if (setLanguageMessageBuilder_ == null) {
        if (setLanguageMessage_ != null) {
          setLanguageMessage_ =
            com.stupidbeauty.hxlauncher.SetLanguageReq.newBuilder(setLanguageMessage_).mergeFrom(value).buildPartial();
        } else {
          setLanguageMessage_ = value;
        }
        onChanged();
      } else {
        setLanguageMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public Builder clearSetLanguageMessage() {
      if (setLanguageMessageBuilder_ == null) {
        setLanguageMessage_ = null;
        onChanged();
      } else {
        setLanguageMessage_ = null;
        setLanguageMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public com.stupidbeauty.hxlauncher.SetLanguageReq.Builder getSetLanguageMessageBuilder() {
      
      onChanged();
      return getSetLanguageMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    public com.stupidbeauty.hxlauncher.SetLanguageReqOrBuilder getSetLanguageMessageOrBuilder() {
      if (setLanguageMessageBuilder_ != null) {
        return setLanguageMessageBuilder_.getMessageOrBuilder();
      } else {
        return setLanguageMessage_ == null ?
            com.stupidbeauty.hxlauncher.SetLanguageReq.getDefaultInstance() : setLanguageMessage_;
      }
    }
    /**
     * <pre>
     *设置工作语言的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.SetLanguageReq setLanguageMessage = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.SetLanguageReq, com.stupidbeauty.hxlauncher.SetLanguageReq.Builder, com.stupidbeauty.hxlauncher.SetLanguageReqOrBuilder> 
        getSetLanguageMessageFieldBuilder() {
      if (setLanguageMessageBuilder_ == null) {
        setLanguageMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.hxlauncher.SetLanguageReq, com.stupidbeauty.hxlauncher.SetLanguageReq.Builder, com.stupidbeauty.hxlauncher.SetLanguageReqOrBuilder>(
                getSetLanguageMessage(),
                getParentForChildren(),
                isClean());
        setLanguageMessage_ = null;
      }
      return setLanguageMessageBuilder_;
    }

    private com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq, com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.Builder, com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder> reportAudioSoundSourceReqMessageBuilder_;
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public boolean hasReportAudioSoundSourceReqMessage() {
      return reportAudioSoundSourceReqMessageBuilder_ != null || reportAudioSoundSourceReqMessage_ != null;
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq getReportAudioSoundSourceReqMessage() {
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        return reportAudioSoundSourceReqMessage_ == null ? com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.getDefaultInstance() : reportAudioSoundSourceReqMessage_;
      } else {
        return reportAudioSoundSourceReqMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public Builder setReportAudioSoundSourceReqMessage(com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq value) {
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reportAudioSoundSourceReqMessage_ = value;
        onChanged();
      } else {
        reportAudioSoundSourceReqMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public Builder setReportAudioSoundSourceReqMessage(
        com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.Builder builderForValue) {
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        reportAudioSoundSourceReqMessage_ = builderForValue.build();
        onChanged();
      } else {
        reportAudioSoundSourceReqMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public Builder mergeReportAudioSoundSourceReqMessage(com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq value) {
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        if (reportAudioSoundSourceReqMessage_ != null) {
          reportAudioSoundSourceReqMessage_ =
            com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.newBuilder(reportAudioSoundSourceReqMessage_).mergeFrom(value).buildPartial();
        } else {
          reportAudioSoundSourceReqMessage_ = value;
        }
        onChanged();
      } else {
        reportAudioSoundSourceReqMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public Builder clearReportAudioSoundSourceReqMessage() {
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        reportAudioSoundSourceReqMessage_ = null;
        onChanged();
      } else {
        reportAudioSoundSourceReqMessage_ = null;
        reportAudioSoundSourceReqMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.Builder getReportAudioSoundSourceReqMessageBuilder() {
      
      onChanged();
      return getReportAudioSoundSourceReqMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    public com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder getReportAudioSoundSourceReqMessageOrBuilder() {
      if (reportAudioSoundSourceReqMessageBuilder_ != null) {
        return reportAudioSoundSourceReqMessageBuilder_.getMessageOrBuilder();
      } else {
        return reportAudioSoundSourceReqMessage_ == null ?
            com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.getDefaultInstance() : reportAudioSoundSourceReqMessage_;
      }
    }
    /**
     * <pre>
     *报告语音输入设备源的消息体。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq reportAudioSoundSourceReqMessage = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq, com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.Builder, com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder> 
        getReportAudioSoundSourceReqMessageFieldBuilder() {
      if (reportAudioSoundSourceReqMessageBuilder_ == null) {
        reportAudioSoundSourceReqMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq, com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReq.Builder, com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqOrBuilder>(
                getReportAudioSoundSourceReqMessage(),
                getParentForChildren(),
                isClean());
        reportAudioSoundSourceReqMessage_ = null;
      }
      return reportAudioSoundSourceReqMessageBuilder_;
    }

    private com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq, com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.Builder, com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder> set3DEngineCameraPositionRotationMessageBuilder_;
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public boolean hasSet3DEngineCameraPositionRotationMessage() {
      return set3DEngineCameraPositionRotationMessageBuilder_ != null || set3DEngineCameraPositionRotationMessage_ != null;
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq getSet3DEngineCameraPositionRotationMessage() {
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        return set3DEngineCameraPositionRotationMessage_ == null ? com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.getDefaultInstance() : set3DEngineCameraPositionRotationMessage_;
      } else {
        return set3DEngineCameraPositionRotationMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public Builder setSet3DEngineCameraPositionRotationMessage(com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq value) {
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        set3DEngineCameraPositionRotationMessage_ = value;
        onChanged();
      } else {
        set3DEngineCameraPositionRotationMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public Builder setSet3DEngineCameraPositionRotationMessage(
        com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.Builder builderForValue) {
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        set3DEngineCameraPositionRotationMessage_ = builderForValue.build();
        onChanged();
      } else {
        set3DEngineCameraPositionRotationMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public Builder mergeSet3DEngineCameraPositionRotationMessage(com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq value) {
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        if (set3DEngineCameraPositionRotationMessage_ != null) {
          set3DEngineCameraPositionRotationMessage_ =
            com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.newBuilder(set3DEngineCameraPositionRotationMessage_).mergeFrom(value).buildPartial();
        } else {
          set3DEngineCameraPositionRotationMessage_ = value;
        }
        onChanged();
      } else {
        set3DEngineCameraPositionRotationMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public Builder clearSet3DEngineCameraPositionRotationMessage() {
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        set3DEngineCameraPositionRotationMessage_ = null;
        onChanged();
      } else {
        set3DEngineCameraPositionRotationMessage_ = null;
        set3DEngineCameraPositionRotationMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.Builder getSet3DEngineCameraPositionRotationMessageBuilder() {
      
      onChanged();
      return getSet3DEngineCameraPositionRotationMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    public com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder getSet3DEngineCameraPositionRotationMessageOrBuilder() {
      if (set3DEngineCameraPositionRotationMessageBuilder_ != null) {
        return set3DEngineCameraPositionRotationMessageBuilder_.getMessageOrBuilder();
      } else {
        return set3DEngineCameraPositionRotationMessage_ == null ?
            com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.getDefaultInstance() : set3DEngineCameraPositionRotationMessage_;
      }
    }
    /**
     * <pre>
     *设置三维人像的渲染相机位置及角度。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq set3DEngineCameraPositionRotationMessage = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq, com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.Builder, com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder> 
        getSet3DEngineCameraPositionRotationMessageFieldBuilder() {
      if (set3DEngineCameraPositionRotationMessageBuilder_ == null) {
        set3DEngineCameraPositionRotationMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq, com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq.Builder, com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqOrBuilder>(
                getSet3DEngineCameraPositionRotationMessage(),
                getParentForChildren(),
                isClean());
        set3DEngineCameraPositionRotationMessage_ = null;
      }
      return set3DEngineCameraPositionRotationMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.AndroidApplicationMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.AndroidApplicationMessage)
  private static final com.stupidbeauty.hxlauncher.AndroidApplicationMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.AndroidApplicationMessage();
  }

  public static com.stupidbeauty.hxlauncher.AndroidApplicationMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AndroidApplicationMessage>
      PARSER = new com.google.protobuf.AbstractParser<AndroidApplicationMessage>() {
    @java.lang.Override
    public AndroidApplicationMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AndroidApplicationMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AndroidApplicationMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AndroidApplicationMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.AndroidApplicationMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

