// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DummyReply.proto

package com.stupidbeauty.hxlauncher;

public interface DummyReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.DummyReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 返回结果头部
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReplyHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <pre>
   * 返回结果头部
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReplyHeader header = 1;</code>
   */
  com.stupidbeauty.hxlauncher.ReplyHeader getHeader();
  /**
   * <pre>
   * 返回结果头部
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReplyHeader header = 1;</code>
   */
  com.stupidbeauty.hxlauncher.ReplyHeaderOrBuilder getHeaderOrBuilder();
}
