// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetHumanBodyDetectStatusReply.proto

package com.stupidbeauty.hxlauncher;

public final class GetHumanBodyDetectStatusReplyProtos {
  private GetHumanBodyDetectStatusReplyProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_GetHumanBodyDetectStatusReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_GetHumanBodyDetectStatusReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#GetHumanBodyDetectStatusReply.proto\022\033c" +
      "om.stupidbeauty.hxlauncher\032\021ReplyHeader." +
      "proto\"p\n\035GetHumanBodyDetectStatusReply\0228" +
      "\n\006header\030\001 \001(\0132(.com.stupidbeauty.hxlaun" +
      "cher.ReplyHeader\022\025\n\rstatusContent\030\002 \001(\tB" +
      "D\n\033com.stupidbeauty.hxlauncherB#GetHuman" +
      "BodyDetectStatusReplyProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReplyHeaderProtos.getDescriptor(),
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_GetHumanBodyDetectStatusReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_GetHumanBodyDetectStatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_GetHumanBodyDetectStatusReply_descriptor,
        new java.lang.String[] { "Header", "StatusContent", });
    com.stupidbeauty.hxlauncher.ReplyHeaderProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
