// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GetTTSEnginesResponseMessage.proto

package com.stupidbeauty.hxlauncher;

public final class GetTTSEnginesResponseMessageProtos {
  private GetTTSEnginesResponseMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_GetTTSEnginesResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_GetTTSEnginesResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"GetTTSEnginesResponseMessage.proto\022\033co" +
      "m.stupidbeauty.hxlauncher\032\037ReportAudioSo" +
      "undSourceReq.proto\032\034TTSEngineRecordMessa" +
      "ge.proto\"\343\001\n\034GetTTSEnginesResponseMessag" +
      "e\022\013\n\003ret\030\001 \001(\005\022\016\n\006errmsg\030\002 \001(\t\022D\n\007record" +
      "s\030\003 \003(\01323.com.stupidbeauty.hxlauncher.TT" +
      "SEngineRecordMessage\022`\n reportAudioSound" +
      "SourceReqMessage\030\006 \001(\01326.com.stupidbeaut" +
      "y.hxlauncher.ReportAudioSoundSourceReqBC" +
      "\n\033com.stupidbeauty.hxlauncherB\"GetTTSEng" +
      "inesResponseMessageProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.TTSEngineRecordMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_GetTTSEnginesResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_GetTTSEnginesResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_GetTTSEnginesResponseMessage_descriptor,
        new java.lang.String[] { "Ret", "Errmsg", "Records", "ReportAudioSoundSourceReqMessage", });
    com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.TTSEngineRecordMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
