// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LicenseSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

public final class LicenseSubSystemMessageProtos {
  private LicenseSubSystemMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_LicenseSubSystemMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_LicenseSubSystemMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035LicenseSubSystemMessage.proto\022\033com.stu" +
      "pidbeauty.hxlauncher\032\037ReportAudioSoundSo" +
      "urceReq.proto\032*Set3DEngineCameraPosition" +
      "RotationReq.proto\032\034CameraSubSystemMessag" +
      "e.proto\032\035DisplaySubSystemMessage.proto\"\266" +
      "\003\n\027LicenseSubSystemMessage\022\030\n\020licenseSer" +
      "verUrl\030\001 \001(\t\022S\n\026cameraSubSystemMessage\030\002" +
      " \001(\01323.com.stupidbeauty.hxlauncher.Camer" +
      "aSubSystemMessage\022U\n\027displaySubSystemMes" +
      "sage\030\003 \001(\01324.com.stupidbeauty.hxlauncher" +
      ".DisplaySubSystemMessage\022`\n reportAudioS" +
      "oundSourceReqMessage\030\006 \001(\01326.com.stupidb" +
      "eauty.hxlauncher.ReportAudioSoundSourceR" +
      "eq\022s\n(set3DEngineCameraPositionRotationM" +
      "essage\030\010 \001(\0132A.com.stupidbeauty.hxlaunch" +
      "er.Set3DEngineCameraPositionRotationReqB" +
      ">\n\033com.stupidbeauty.hxlauncherB\035LicenseS" +
      "ubSystemMessageProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.CameraSubSystemMessageProtos.getDescriptor(),
          com.stupidbeauty.hxlauncher.DisplaySubSystemMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_LicenseSubSystemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_LicenseSubSystemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_LicenseSubSystemMessage_descriptor,
        new java.lang.String[] { "LicenseServerUrl", "CameraSubSystemMessage", "DisplaySubSystemMessage", "ReportAudioSoundSourceReqMessage", "Set3DEngineCameraPositionRotationMessage", });
    com.stupidbeauty.hxlauncher.ReportAudioSoundSourceReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReqProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.CameraSubSystemMessageProtos.getDescriptor();
    com.stupidbeauty.hxlauncher.DisplaySubSystemMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
