// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitorSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.MonitorSubSystemMessage}
 */
public  final class MonitorSubSystemMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)
    MonitorSubSystemMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MonitorSubSystemMessage.newBuilder() to construct.
  private MonitorSubSystemMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MonitorSubSystemMessage() {
    monitorServiceUrl_ = "";
    robotId_ = "";
    machineCode_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MonitorSubSystemMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            monitorServiceUrl_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            robotId_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            machineCode_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.MonitorSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_MonitorSubSystemMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.MonitorSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_MonitorSubSystemMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.class, com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.Builder.class);
  }

  public static final int MONITORSERVICEURL_FIELD_NUMBER = 1;
  private volatile java.lang.Object monitorServiceUrl_;
  /**
   * <pre>
   *监控服务网址。
   * </pre>
   *
   * <code>string monitorServiceUrl = 1;</code>
   */
  public java.lang.String getMonitorServiceUrl() {
    java.lang.Object ref = monitorServiceUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      monitorServiceUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *监控服务网址。
   * </pre>
   *
   * <code>string monitorServiceUrl = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMonitorServiceUrlBytes() {
    java.lang.Object ref = monitorServiceUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      monitorServiceUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROBOTID_FIELD_NUMBER = 2;
  private volatile java.lang.Object robotId_;
  /**
   * <pre>
   *机器编号。
   * </pre>
   *
   * <code>string robotId = 2;</code>
   */
  public java.lang.String getRobotId() {
    java.lang.Object ref = robotId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      robotId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *机器编号。
   * </pre>
   *
   * <code>string robotId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getRobotIdBytes() {
    java.lang.Object ref = robotId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      robotId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MACHINECODE_FIELD_NUMBER = 3;
  private volatile java.lang.Object machineCode_;
  /**
   * <pre>
   *简短的机器编码。
   * </pre>
   *
   * <code>string machineCode = 3;</code>
   */
  public java.lang.String getMachineCode() {
    java.lang.Object ref = machineCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      machineCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *简短的机器编码。
   * </pre>
   *
   * <code>string machineCode = 3;</code>
   */
  public com.google.protobuf.ByteString
      getMachineCodeBytes() {
    java.lang.Object ref = machineCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      machineCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMonitorServiceUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, monitorServiceUrl_);
    }
    if (!getRobotIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, robotId_);
    }
    if (!getMachineCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, machineCode_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMonitorServiceUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, monitorServiceUrl_);
    }
    if (!getRobotIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, robotId_);
    }
    if (!getMachineCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, machineCode_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.MonitorSubSystemMessage other = (com.stupidbeauty.hxlauncher.MonitorSubSystemMessage) obj;

    boolean result = true;
    result = result && getMonitorServiceUrl()
        .equals(other.getMonitorServiceUrl());
    result = result && getRobotId()
        .equals(other.getRobotId());
    result = result && getMachineCode()
        .equals(other.getMachineCode());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MONITORSERVICEURL_FIELD_NUMBER;
    hash = (53 * hash) + getMonitorServiceUrl().hashCode();
    hash = (37 * hash) + ROBOTID_FIELD_NUMBER;
    hash = (53 * hash) + getRobotId().hashCode();
    hash = (37 * hash) + MACHINECODE_FIELD_NUMBER;
    hash = (53 * hash) + getMachineCode().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.MonitorSubSystemMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.MonitorSubSystemMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)
      com.stupidbeauty.hxlauncher.MonitorSubSystemMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.MonitorSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_MonitorSubSystemMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.MonitorSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_MonitorSubSystemMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.class, com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      monitorServiceUrl_ = "";

      robotId_ = "";

      machineCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.MonitorSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_MonitorSubSystemMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.MonitorSubSystemMessage getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.MonitorSubSystemMessage build() {
      com.stupidbeauty.hxlauncher.MonitorSubSystemMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.MonitorSubSystemMessage buildPartial() {
      com.stupidbeauty.hxlauncher.MonitorSubSystemMessage result = new com.stupidbeauty.hxlauncher.MonitorSubSystemMessage(this);
      result.monitorServiceUrl_ = monitorServiceUrl_;
      result.robotId_ = robotId_;
      result.machineCode_ = machineCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.MonitorSubSystemMessage) {
        return mergeFrom((com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.MonitorSubSystemMessage other) {
      if (other == com.stupidbeauty.hxlauncher.MonitorSubSystemMessage.getDefaultInstance()) return this;
      if (!other.getMonitorServiceUrl().isEmpty()) {
        monitorServiceUrl_ = other.monitorServiceUrl_;
        onChanged();
      }
      if (!other.getRobotId().isEmpty()) {
        robotId_ = other.robotId_;
        onChanged();
      }
      if (!other.getMachineCode().isEmpty()) {
        machineCode_ = other.machineCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.MonitorSubSystemMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.MonitorSubSystemMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object monitorServiceUrl_ = "";
    /**
     * <pre>
     *监控服务网址。
     * </pre>
     *
     * <code>string monitorServiceUrl = 1;</code>
     */
    public java.lang.String getMonitorServiceUrl() {
      java.lang.Object ref = monitorServiceUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        monitorServiceUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *监控服务网址。
     * </pre>
     *
     * <code>string monitorServiceUrl = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMonitorServiceUrlBytes() {
      java.lang.Object ref = monitorServiceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        monitorServiceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *监控服务网址。
     * </pre>
     *
     * <code>string monitorServiceUrl = 1;</code>
     */
    public Builder setMonitorServiceUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      monitorServiceUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *监控服务网址。
     * </pre>
     *
     * <code>string monitorServiceUrl = 1;</code>
     */
    public Builder clearMonitorServiceUrl() {
      
      monitorServiceUrl_ = getDefaultInstance().getMonitorServiceUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *监控服务网址。
     * </pre>
     *
     * <code>string monitorServiceUrl = 1;</code>
     */
    public Builder setMonitorServiceUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      monitorServiceUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object robotId_ = "";
    /**
     * <pre>
     *机器编号。
     * </pre>
     *
     * <code>string robotId = 2;</code>
     */
    public java.lang.String getRobotId() {
      java.lang.Object ref = robotId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        robotId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *机器编号。
     * </pre>
     *
     * <code>string robotId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRobotIdBytes() {
      java.lang.Object ref = robotId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        robotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *机器编号。
     * </pre>
     *
     * <code>string robotId = 2;</code>
     */
    public Builder setRobotId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      robotId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *机器编号。
     * </pre>
     *
     * <code>string robotId = 2;</code>
     */
    public Builder clearRobotId() {
      
      robotId_ = getDefaultInstance().getRobotId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *机器编号。
     * </pre>
     *
     * <code>string robotId = 2;</code>
     */
    public Builder setRobotIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      robotId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object machineCode_ = "";
    /**
     * <pre>
     *简短的机器编码。
     * </pre>
     *
     * <code>string machineCode = 3;</code>
     */
    public java.lang.String getMachineCode() {
      java.lang.Object ref = machineCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        machineCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *简短的机器编码。
     * </pre>
     *
     * <code>string machineCode = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMachineCodeBytes() {
      java.lang.Object ref = machineCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        machineCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *简短的机器编码。
     * </pre>
     *
     * <code>string machineCode = 3;</code>
     */
    public Builder setMachineCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      machineCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *简短的机器编码。
     * </pre>
     *
     * <code>string machineCode = 3;</code>
     */
    public Builder clearMachineCode() {
      
      machineCode_ = getDefaultInstance().getMachineCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *简短的机器编码。
     * </pre>
     *
     * <code>string machineCode = 3;</code>
     */
    public Builder setMachineCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      machineCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.MonitorSubSystemMessage)
  private static final com.stupidbeauty.hxlauncher.MonitorSubSystemMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.MonitorSubSystemMessage();
  }

  public static com.stupidbeauty.hxlauncher.MonitorSubSystemMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MonitorSubSystemMessage>
      PARSER = new com.google.protobuf.AbstractParser<MonitorSubSystemMessage>() {
    @java.lang.Override
    public MonitorSubSystemMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MonitorSubSystemMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MonitorSubSystemMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MonitorSubSystemMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.MonitorSubSystemMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

