// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OnlineTtsParameterMessage.proto

package com.stupidbeauty.hxlauncher;

public interface OnlineTtsParameterMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.OnlineTtsParameterMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *文字内容。
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *文字内容。
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
