// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PackageAutoRunMapMessage.proto

package com.stupidbeauty.hxlauncher;

public final class PackageItemLaunchCoolDownMapMessageProtos {
  private PackageItemLaunchCoolDownMapMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PackageItemLaunchCoolDownMapMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    java.util.List<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage> 
        getMapList();
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage getMap(int index);
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    int getMapCount();
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    java.util.List<? extends com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder> 
        getMapOrBuilderList();
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder getMapOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage}
   */
  public  static final class PackageItemLaunchCoolDownMapMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage)
      PackageItemLaunchCoolDownMapMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageItemLaunchCoolDownMapMessage.newBuilder() to construct.
    private PackageItemLaunchCoolDownMapMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageItemLaunchCoolDownMapMessage() {
      map_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageItemLaunchCoolDownMapMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                map_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage>();
                mutable_bitField0_ |= 0x00000001;
              }
              map_.add(
                  input.readMessage(com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          map_ = java.util.Collections.unmodifiableList(map_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.class, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.Builder.class);
    }

    public static final int MAP_FIELD_NUMBER = 1;
    private java.util.List<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage> map_;
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    public java.util.List<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage> getMapList() {
      return map_;
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    public java.util.List<? extends com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder> 
        getMapOrBuilderList() {
      return map_;
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    public int getMapCount() {
      return map_.size();
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage getMap(int index) {
      return map_.get(index);
    }
    /**
     * <pre>
     *映射数据体。
     * </pre>
     *
     * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
     */
    public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder getMapOrBuilder(
        int index) {
      return map_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < map_.size(); i++) {
        output.writeMessage(1, map_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < map_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, map_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage)) {
        return super.equals(obj);
      }
      com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage other = (com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage) obj;

      boolean result = true;
      result = result && getMapList()
          .equals(other.getMapList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getMapCount() > 0) {
        hash = (37 * hash) + MAP_FIELD_NUMBER;
        hash = (53 * hash) + getMapList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage)
        com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.class, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.Builder.class);
      }

      // Construct using com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMapFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mapBuilder_ == null) {
          map_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          mapBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_descriptor;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage getDefaultInstanceForType() {
        return com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage build() {
        com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage buildPartial() {
        com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage result = new com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage(this);
        int from_bitField0_ = bitField0_;
        if (mapBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            map_ = java.util.Collections.unmodifiableList(map_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.map_ = map_;
        } else {
          result.map_ = mapBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage) {
          return mergeFrom((com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage other) {
        if (other == com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage.getDefaultInstance()) return this;
        if (mapBuilder_ == null) {
          if (!other.map_.isEmpty()) {
            if (map_.isEmpty()) {
              map_ = other.map_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureMapIsMutable();
              map_.addAll(other.map_);
            }
            onChanged();
          }
        } else {
          if (!other.map_.isEmpty()) {
            if (mapBuilder_.isEmpty()) {
              mapBuilder_.dispose();
              mapBuilder_ = null;
              map_ = other.map_;
              bitField0_ = (bitField0_ & ~0x00000001);
              mapBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMapFieldBuilder() : null;
            } else {
              mapBuilder_.addAllMessages(other.map_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage> map_ =
        java.util.Collections.emptyList();
      private void ensureMapIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          map_ = new java.util.ArrayList<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage>(map_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder> mapBuilder_;

      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage> getMapList() {
        if (mapBuilder_ == null) {
          return java.util.Collections.unmodifiableList(map_);
        } else {
          return mapBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public int getMapCount() {
        if (mapBuilder_ == null) {
          return map_.size();
        } else {
          return mapBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage getMap(int index) {
        if (mapBuilder_ == null) {
          return map_.get(index);
        } else {
          return mapBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder setMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.set(index, value);
          onChanged();
        } else {
          mapBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder setMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.set(index, builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder addMap(com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.add(value);
          onChanged();
        } else {
          mapBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder addMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage value) {
        if (mapBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMapIsMutable();
          map_.add(index, value);
          onChanged();
        } else {
          mapBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder addMap(
          com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.add(builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder addMap(
          int index, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder builderForValue) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.add(index, builderForValue.build());
          onChanged();
        } else {
          mapBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder addAllMap(
          java.lang.Iterable<? extends com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage> values) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, map_);
          onChanged();
        } else {
          mapBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder clearMap() {
        if (mapBuilder_ == null) {
          map_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          mapBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public Builder removeMap(int index) {
        if (mapBuilder_ == null) {
          ensureMapIsMutable();
          map_.remove(index);
          onChanged();
        } else {
          mapBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder getMapBuilder(
          int index) {
        return getMapFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder getMapOrBuilder(
          int index) {
        if (mapBuilder_ == null) {
          return map_.get(index);  } else {
          return mapBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public java.util.List<? extends com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder> 
           getMapOrBuilderList() {
        if (mapBuilder_ != null) {
          return mapBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(map_);
        }
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder addMapBuilder() {
        return getMapFieldBuilder().addBuilder(
            com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder addMapBuilder(
          int index) {
        return getMapFieldBuilder().addBuilder(
            index, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.getDefaultInstance());
      }
      /**
       * <pre>
       *映射数据体。
       * </pre>
       *
       * <code>repeated .com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessage map = 1;</code>
       */
      public java.util.List<com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder> 
           getMapBuilderList() {
        return getMapFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder> 
          getMapFieldBuilder() {
        if (mapBuilder_ == null) {
          mapBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessage.Builder, com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.PackageItemLaunchCoolDownMapItemMessageOrBuilder>(
                  map_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          map_ = null;
        }
        return mapBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage)
    }

    // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessage)
    private static final com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage();
    }

    public static com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageItemLaunchCoolDownMapMessage>
        PARSER = new com.google.protobuf.AbstractParser<PackageItemLaunchCoolDownMapMessage>() {
      @java.lang.Override
      public PackageItemLaunchCoolDownMapMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageItemLaunchCoolDownMapMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageItemLaunchCoolDownMapMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageItemLaunchCoolDownMapMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapMessageProtos.PackageItemLaunchCoolDownMapMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036PackageAutoRunMapMessage.proto\022\033com.st" +
      "upidbeauty.hxlauncher\032-PackageItemLaunch" +
      "CoolDownMapItemMessage.proto\"x\n#PackageI" +
      "temLaunchCoolDownMapMessage\022Q\n\003map\030\001 \003(\013" +
      "2D.com.stupidbeauty.hxlauncher.PackageIt" +
      "emLaunchCoolDownMapItemMessageBH\n\033com.st" +
      "upidbeauty.hxlauncherB)PackageItemLaunch" +
      "CoolDownMapMessageProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.getDescriptor(),
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_PackageItemLaunchCoolDownMapMessage_descriptor,
        new java.lang.String[] { "Map", });
    com.stupidbeauty.hxlauncher.PackageItemLaunchCoolDownMapItemMessageProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
