// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportMacroVoiceFinishedReq.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq}
 */
public  final class ReportMacroVoiceFinishedReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq)
    ReportMacroVoiceFinishedReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportMacroVoiceFinishedReq.newBuilder() to construct.
  private ReportMacroVoiceFinishedReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportMacroVoiceFinishedReq() {
    macroId_ = "";
    macroVoiceResult_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportMacroVoiceFinishedReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            macroId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            macroVoiceResult_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroVoiceFinishedReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroVoiceFinishedReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.class, com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.Builder.class);
  }

  public static final int MACROID_FIELD_NUMBER = 1;
  private volatile java.lang.Object macroId_;
  /**
   * <pre>
   *宏编号。
   * </pre>
   *
   * <code>string macroId = 1;</code>
   */
  public java.lang.String getMacroId() {
    java.lang.Object ref = macroId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      macroId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *宏编号。
   * </pre>
   *
   * <code>string macroId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getMacroIdBytes() {
    java.lang.Object ref = macroId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      macroId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MACROVOICERESULT_FIELD_NUMBER = 2;
  private volatile java.lang.Object macroVoiceResult_;
  /**
   * <pre>
   *宏语音执行结果。
   * </pre>
   *
   * <code>string macroVoiceResult = 2;</code>
   */
  public java.lang.String getMacroVoiceResult() {
    java.lang.Object ref = macroVoiceResult_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      macroVoiceResult_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *宏语音执行结果。
   * </pre>
   *
   * <code>string macroVoiceResult = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMacroVoiceResultBytes() {
    java.lang.Object ref = macroVoiceResult_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      macroVoiceResult_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getMacroIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, macroId_);
    }
    if (!getMacroVoiceResultBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, macroVoiceResult_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getMacroIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, macroId_);
    }
    if (!getMacroVoiceResultBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, macroVoiceResult_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq other = (com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq) obj;

    boolean result = true;
    result = result && getMacroId()
        .equals(other.getMacroId());
    result = result && getMacroVoiceResult()
        .equals(other.getMacroVoiceResult());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MACROID_FIELD_NUMBER;
    hash = (53 * hash) + getMacroId().hashCode();
    hash = (37 * hash) + MACROVOICERESULT_FIELD_NUMBER;
    hash = (53 * hash) + getMacroVoiceResult().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq)
      com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroVoiceFinishedReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroVoiceFinishedReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.class, com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      macroId_ = "";

      macroVoiceResult_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReqProtos.internal_static_com_stupidbeauty_hxlauncher_ReportMacroVoiceFinishedReq_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq build() {
      com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq buildPartial() {
      com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq result = new com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq(this);
      result.macroId_ = macroId_;
      result.macroVoiceResult_ = macroVoiceResult_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq) {
        return mergeFrom((com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq other) {
      if (other == com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq.getDefaultInstance()) return this;
      if (!other.getMacroId().isEmpty()) {
        macroId_ = other.macroId_;
        onChanged();
      }
      if (!other.getMacroVoiceResult().isEmpty()) {
        macroVoiceResult_ = other.macroVoiceResult_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object macroId_ = "";
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     */
    public java.lang.String getMacroId() {
      java.lang.Object ref = macroId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macroId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMacroIdBytes() {
      java.lang.Object ref = macroId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macroId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     */
    public Builder setMacroId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macroId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     */
    public Builder clearMacroId() {
      
      macroId_ = getDefaultInstance().getMacroId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏编号。
     * </pre>
     *
     * <code>string macroId = 1;</code>
     */
    public Builder setMacroIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      macroId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object macroVoiceResult_ = "";
    /**
     * <pre>
     *宏语音执行结果。
     * </pre>
     *
     * <code>string macroVoiceResult = 2;</code>
     */
    public java.lang.String getMacroVoiceResult() {
      java.lang.Object ref = macroVoiceResult_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        macroVoiceResult_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *宏语音执行结果。
     * </pre>
     *
     * <code>string macroVoiceResult = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMacroVoiceResultBytes() {
      java.lang.Object ref = macroVoiceResult_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        macroVoiceResult_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *宏语音执行结果。
     * </pre>
     *
     * <code>string macroVoiceResult = 2;</code>
     */
    public Builder setMacroVoiceResult(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      macroVoiceResult_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏语音执行结果。
     * </pre>
     *
     * <code>string macroVoiceResult = 2;</code>
     */
    public Builder clearMacroVoiceResult() {
      
      macroVoiceResult_ = getDefaultInstance().getMacroVoiceResult();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *宏语音执行结果。
     * </pre>
     *
     * <code>string macroVoiceResult = 2;</code>
     */
    public Builder setMacroVoiceResultBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      macroVoiceResult_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq)
  private static final com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq();
  }

  public static com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportMacroVoiceFinishedReq>
      PARSER = new com.google.protobuf.AbstractParser<ReportMacroVoiceFinishedReq>() {
    @java.lang.Override
    public ReportMacroVoiceFinishedReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportMacroVoiceFinishedReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportMacroVoiceFinishedReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportMacroVoiceFinishedReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.ReportMacroVoiceFinishedReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

