// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportFaceRecognizeResultReq.proto

package com.stupidbeauty.hxlauncher;

public interface ReportFaceRecognizeResultReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportFaceRecognizeResultReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *结果字符串。
   * </pre>
   *
   * <code>string resultString = 1;</code>
   */
  java.lang.String getResultString();
  /**
   * <pre>
   *结果字符串。
   * </pre>
   *
   * <code>string resultString = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultStringBytes();
}
