// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportVoiceRecognizedReq.proto

package com.stupidbeauty.hxlauncher;

public final class ReportVoiceRecognizedReqProtos {
  private ReportVoiceRecognizedReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_ReportVoiceRecognizedReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_ReportVoiceRecognizedReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036ReportVoiceRecognizedReq.proto\022\033com.st" +
      "upidbeauty.hxlauncher\"8\n\030ReportVoiceReco" +
      "gnizedReq\022\014\n\004text\030\001 \001(\t\022\016\n\006isOver\030\002 \001(\010B" +
      "?\n\033com.stupidbeauty.hxlauncherB\036ReportVo" +
      "iceRecognizedReqProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_ReportVoiceRecognizedReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_ReportVoiceRecognizedReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_ReportVoiceRecognizedReq_descriptor,
        new java.lang.String[] { "Text", "IsOver", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
