// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ReportVoiceRecognizedReq.proto

package com.stupidbeauty.hxlauncher;

public interface ReportVoiceRecognizedReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *识别出来的文字。
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  java.lang.String getText();
  /**
   * <pre>
   *识别出来的文字。
   * </pre>
   *
   * <code>string text = 1;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <pre>
   *是否完整识别完毕。
   * </pre>
   *
   * <code>bool isOver = 2;</code>
   */
  boolean getIsOver();
}
