// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Set3DEngineCameraPositionRotationReq.proto

package com.stupidbeauty.hxlauncher;

public interface Set3DEngineCameraPositionRotationReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.Set3DEngineCameraPositionRotationReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *X坐标。
   * </pre>
   *
   * <code>float x = 1;</code>
   */
  float getX();

  /**
   * <pre>
   *Y坐标。
   * </pre>
   *
   * <code>float y = 2;</code>
   */
  float getY();

  /**
   * <pre>
   *Z坐标。
   * </pre>
   *
   * <code>float z = 3;</code>
   */
  float getZ();

  /**
   * <pre>
   *俯仰角。
   * </pre>
   *
   * <code>float pitch = 4;</code>
   */
  float getPitch();

  /**
   * <pre>
   *翻滚角。
   * </pre>
   *
   * <code>float roll = 5;</code>
   */
  float getRoll();

  /**
   * <pre>
   *航向角。
   * </pre>
   *
   * <code>float yaw = 6;</code>
   */
  float getYaw();
}
