// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SetAvatarVisibleReq.proto

package com.stupidbeauty.hxlauncher;

public interface SetAvatarVisibleReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.stupidbeauty.hxlauncher.SetAvatarVisibleReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *是否可见。
   * </pre>
   *
   * <code>bool visible = 1;</code>
   */
  boolean getVisible();
}
