// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SetMultiTouchEnabledReq.proto

package com.stupidbeauty.hxlauncher;

public final class SetMultiTouchEnabledReqProtos {
  private SetMultiTouchEnabledReqProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_stupidbeauty_hxlauncher_SetMultiTouchEnabledReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_stupidbeauty_hxlauncher_SetMultiTouchEnabledReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035SetMultiTouchEnabledReq.proto\022\033com.stu" +
      "pidbeauty.hxlauncher\"*\n\027SetMultiTouchEna" +
      "bledReq\022\017\n\007enabled\030\001 \001(\010B>\n\033com.stupidbe" +
      "auty.hxlauncherB\035SetMultiTouchEnabledReq" +
      "ProtosP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_stupidbeauty_hxlauncher_SetMultiTouchEnabledReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_stupidbeauty_hxlauncher_SetMultiTouchEnabledReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_stupidbeauty_hxlauncher_SetMultiTouchEnabledReq_descriptor,
        new java.lang.String[] { "Enabled", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
