// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpeakerSubSystemMessage.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage}
 */
public  final class SpeakerSubSystemMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)
    SpeakerSubSystemMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SpeakerSubSystemMessage.newBuilder() to construct.
  private SpeakerSubSystemMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SpeakerSubSystemMessage() {
    ttsEngine_ = "";
    ttsEngineYueHantHk_ = "";
    ttsEngineEnUs_ = "";
    xiaoINuanceServiceUrl_ = "";
    biaobeiServiceUrl_ = "";
    biaobeiServiceUserId_ = "";
    xunfeiSdkAppId_ = "";
    xunfeiSdkLibMscSoDirectory_ = "";
    sppasToolsIp_ = "";
    cacheDirectory_ = "";
    speed_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SpeakerSubSystemMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            ttsEngine_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            ttsEngineYueHantHk_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            ttsEngineEnUs_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            xiaoINuanceServiceUrl_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            biaobeiServiceUrl_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            biaobeiServiceUserId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            xunfeiSdkAppId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            xunfeiSdkLibMscSoDirectory_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            sppasToolsIp_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            cacheDirectory_ = s;
            break;
          }
          case 88: {

            speed_ = input.readInt32();
            break;
          }
          case 154: {
            com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.Builder subBuilder = null;
            if (reportAccurateVoiceCommandMessage_ != null) {
              subBuilder = reportAccurateVoiceCommandMessage_.toBuilder();
            }
            reportAccurateVoiceCommandMessage_ = input.readMessage(com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reportAccurateVoiceCommandMessage_);
              reportAccurateVoiceCommandMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          case 162: {
            com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.Builder subBuilder = null;
            if (reportVoiceRecognizedMessage_ != null) {
              subBuilder = reportVoiceRecognizedMessage_.toBuilder();
            }
            reportVoiceRecognizedMessage_ = input.readMessage(com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(reportVoiceRecognizedMessage_);
              reportVoiceRecognizedMessage_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.SpeakerSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_SpeakerSubSystemMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.SpeakerSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_SpeakerSubSystemMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.class, com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.Builder.class);
  }

  public static final int TTSENGINE_FIELD_NUMBER = 1;
  private volatile java.lang.Object ttsEngine_;
  /**
   * <pre>
   *简体中文的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngine = 1;</code>
   */
  public java.lang.String getTtsEngine() {
    java.lang.Object ref = ttsEngine_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ttsEngine_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *简体中文的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngine = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTtsEngineBytes() {
    java.lang.Object ref = ttsEngine_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ttsEngine_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TTSENGINEYUEHANTHK_FIELD_NUMBER = 2;
  private volatile java.lang.Object ttsEngineYueHantHk_;
  /**
   * <pre>
   *广东话的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineYueHantHk = 2;</code>
   */
  public java.lang.String getTtsEngineYueHantHk() {
    java.lang.Object ref = ttsEngineYueHantHk_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ttsEngineYueHantHk_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *广东话的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineYueHantHk = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTtsEngineYueHantHkBytes() {
    java.lang.Object ref = ttsEngineYueHantHk_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ttsEngineYueHantHk_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TTSENGINEENUS_FIELD_NUMBER = 3;
  private volatile java.lang.Object ttsEngineEnUs_;
  /**
   * <pre>
   *英语的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineEnUs = 3;</code>
   */
  public java.lang.String getTtsEngineEnUs() {
    java.lang.Object ref = ttsEngineEnUs_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ttsEngineEnUs_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *英语的语音合成引擎。
   * </pre>
   *
   * <code>string ttsEngineEnUs = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTtsEngineEnUsBytes() {
    java.lang.Object ref = ttsEngineEnUs_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ttsEngineEnUs_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int XIAOINUANCESERVICEURL_FIELD_NUMBER = 4;
  private volatile java.lang.Object xiaoINuanceServiceUrl_;
  /**
   * <pre>
   *Nuance语音合成的引擎地址。
   * </pre>
   *
   * <code>string xiaoINuanceServiceUrl = 4;</code>
   */
  public java.lang.String getXiaoINuanceServiceUrl() {
    java.lang.Object ref = xiaoINuanceServiceUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      xiaoINuanceServiceUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *Nuance语音合成的引擎地址。
   * </pre>
   *
   * <code>string xiaoINuanceServiceUrl = 4;</code>
   */
  public com.google.protobuf.ByteString
      getXiaoINuanceServiceUrlBytes() {
    java.lang.Object ref = xiaoINuanceServiceUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      xiaoINuanceServiceUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIAOBEISERVICEURL_FIELD_NUMBER = 5;
  private volatile java.lang.Object biaobeiServiceUrl_;
  /**
   * <pre>
   *标贝语音合成的服务地址。
   * </pre>
   *
   * <code>string biaobeiServiceUrl = 5;</code>
   */
  public java.lang.String getBiaobeiServiceUrl() {
    java.lang.Object ref = biaobeiServiceUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      biaobeiServiceUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *标贝语音合成的服务地址。
   * </pre>
   *
   * <code>string biaobeiServiceUrl = 5;</code>
   */
  public com.google.protobuf.ByteString
      getBiaobeiServiceUrlBytes() {
    java.lang.Object ref = biaobeiServiceUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      biaobeiServiceUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BIAOBEISERVICEUSERID_FIELD_NUMBER = 6;
  private volatile java.lang.Object biaobeiServiceUserId_;
  /**
   * <pre>
   *标贝语音合成的用户编号。
   * </pre>
   *
   * <code>string biaobeiServiceUserId = 6;</code>
   */
  public java.lang.String getBiaobeiServiceUserId() {
    java.lang.Object ref = biaobeiServiceUserId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      biaobeiServiceUserId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *标贝语音合成的用户编号。
   * </pre>
   *
   * <code>string biaobeiServiceUserId = 6;</code>
   */
  public com.google.protobuf.ByteString
      getBiaobeiServiceUserIdBytes() {
    java.lang.Object ref = biaobeiServiceUserId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      biaobeiServiceUserId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int XUNFEISDKAPPID_FIELD_NUMBER = 7;
  private volatile java.lang.Object xunfeiSdkAppId_;
  /**
   * <pre>
   *设置三维人像的背景图片。
   * </pre>
   *
   * <code>string xunfeiSdkAppId = 7;</code>
   */
  public java.lang.String getXunfeiSdkAppId() {
    java.lang.Object ref = xunfeiSdkAppId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      xunfeiSdkAppId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *设置三维人像的背景图片。
   * </pre>
   *
   * <code>string xunfeiSdkAppId = 7;</code>
   */
  public com.google.protobuf.ByteString
      getXunfeiSdkAppIdBytes() {
    java.lang.Object ref = xunfeiSdkAppId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      xunfeiSdkAppId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int XUNFEISDKLIBMSCSODIRECTORY_FIELD_NUMBER = 8;
  private volatile java.lang.Object xunfeiSdkLibMscSoDirectory_;
  /**
   * <pre>
   *讯飞语音合成的SO文件的目录。
   * </pre>
   *
   * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
   */
  public java.lang.String getXunfeiSdkLibMscSoDirectory() {
    java.lang.Object ref = xunfeiSdkLibMscSoDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      xunfeiSdkLibMscSoDirectory_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *讯飞语音合成的SO文件的目录。
   * </pre>
   *
   * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
   */
  public com.google.protobuf.ByteString
      getXunfeiSdkLibMscSoDirectoryBytes() {
    java.lang.Object ref = xunfeiSdkLibMscSoDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      xunfeiSdkLibMscSoDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPPASTOOLSIP_FIELD_NUMBER = 9;
  private volatile java.lang.Object sppasToolsIp_;
  /**
   * <pre>
   *SPPAS模块的IP。
   * </pre>
   *
   * <code>string sppasToolsIp = 9;</code>
   */
  public java.lang.String getSppasToolsIp() {
    java.lang.Object ref = sppasToolsIp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      sppasToolsIp_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *SPPAS模块的IP。
   * </pre>
   *
   * <code>string sppasToolsIp = 9;</code>
   */
  public com.google.protobuf.ByteString
      getSppasToolsIpBytes() {
    java.lang.Object ref = sppasToolsIp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      sppasToolsIp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CACHEDIRECTORY_FIELD_NUMBER = 10;
  private volatile java.lang.Object cacheDirectory_;
  /**
   * <pre>
   *声音缓存文件目录。
   * </pre>
   *
   * <code>string cacheDirectory = 10;</code>
   */
  public java.lang.String getCacheDirectory() {
    java.lang.Object ref = cacheDirectory_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cacheDirectory_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *声音缓存文件目录。
   * </pre>
   *
   * <code>string cacheDirectory = 10;</code>
   */
  public com.google.protobuf.ByteString
      getCacheDirectoryBytes() {
    java.lang.Object ref = cacheDirectory_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cacheDirectory_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SPEED_FIELD_NUMBER = 11;
  private int speed_;
  /**
   * <pre>
   *语速。
   * </pre>
   *
   * <code>int32 speed = 11;</code>
   */
  public int getSpeed() {
    return speed_;
  }

  public static final int REPORTACCURATEVOICECOMMANDMESSAGE_FIELD_NUMBER = 19;
  private com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage_;
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  public boolean hasReportAccurateVoiceCommandMessage() {
    return reportAccurateVoiceCommandMessage_ != null;
  }
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  public com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq getReportAccurateVoiceCommandMessage() {
    return reportAccurateVoiceCommandMessage_ == null ? com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.getDefaultInstance() : reportAccurateVoiceCommandMessage_;
  }
  /**
   * <pre>
   *报告精确语音指令。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
   */
  public com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder getReportAccurateVoiceCommandMessageOrBuilder() {
    return getReportAccurateVoiceCommandMessage();
  }

  public static final int REPORTVOICERECOGNIZEDMESSAGE_FIELD_NUMBER = 20;
  private com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage_;
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  public boolean hasReportVoiceRecognizedMessage() {
    return reportVoiceRecognizedMessage_ != null;
  }
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  public com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage() {
    return reportVoiceRecognizedMessage_ == null ? com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.getDefaultInstance() : reportVoiceRecognizedMessage_;
  }
  /**
   * <pre>
   *报告语音识别结果。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
   */
  public com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder() {
    return getReportVoiceRecognizedMessage();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTtsEngineBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ttsEngine_);
    }
    if (!getTtsEngineYueHantHkBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ttsEngineYueHantHk_);
    }
    if (!getTtsEngineEnUsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, ttsEngineEnUs_);
    }
    if (!getXiaoINuanceServiceUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, xiaoINuanceServiceUrl_);
    }
    if (!getBiaobeiServiceUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, biaobeiServiceUrl_);
    }
    if (!getBiaobeiServiceUserIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, biaobeiServiceUserId_);
    }
    if (!getXunfeiSdkAppIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, xunfeiSdkAppId_);
    }
    if (!getXunfeiSdkLibMscSoDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, xunfeiSdkLibMscSoDirectory_);
    }
    if (!getSppasToolsIpBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, sppasToolsIp_);
    }
    if (!getCacheDirectoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, cacheDirectory_);
    }
    if (speed_ != 0) {
      output.writeInt32(11, speed_);
    }
    if (reportAccurateVoiceCommandMessage_ != null) {
      output.writeMessage(19, getReportAccurateVoiceCommandMessage());
    }
    if (reportVoiceRecognizedMessage_ != null) {
      output.writeMessage(20, getReportVoiceRecognizedMessage());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTtsEngineBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ttsEngine_);
    }
    if (!getTtsEngineYueHantHkBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ttsEngineYueHantHk_);
    }
    if (!getTtsEngineEnUsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, ttsEngineEnUs_);
    }
    if (!getXiaoINuanceServiceUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, xiaoINuanceServiceUrl_);
    }
    if (!getBiaobeiServiceUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, biaobeiServiceUrl_);
    }
    if (!getBiaobeiServiceUserIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, biaobeiServiceUserId_);
    }
    if (!getXunfeiSdkAppIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, xunfeiSdkAppId_);
    }
    if (!getXunfeiSdkLibMscSoDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, xunfeiSdkLibMscSoDirectory_);
    }
    if (!getSppasToolsIpBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, sppasToolsIp_);
    }
    if (!getCacheDirectoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, cacheDirectory_);
    }
    if (speed_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(11, speed_);
    }
    if (reportAccurateVoiceCommandMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(19, getReportAccurateVoiceCommandMessage());
    }
    if (reportVoiceRecognizedMessage_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getReportVoiceRecognizedMessage());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage other = (com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage) obj;

    boolean result = true;
    result = result && getTtsEngine()
        .equals(other.getTtsEngine());
    result = result && getTtsEngineYueHantHk()
        .equals(other.getTtsEngineYueHantHk());
    result = result && getTtsEngineEnUs()
        .equals(other.getTtsEngineEnUs());
    result = result && getXiaoINuanceServiceUrl()
        .equals(other.getXiaoINuanceServiceUrl());
    result = result && getBiaobeiServiceUrl()
        .equals(other.getBiaobeiServiceUrl());
    result = result && getBiaobeiServiceUserId()
        .equals(other.getBiaobeiServiceUserId());
    result = result && getXunfeiSdkAppId()
        .equals(other.getXunfeiSdkAppId());
    result = result && getXunfeiSdkLibMscSoDirectory()
        .equals(other.getXunfeiSdkLibMscSoDirectory());
    result = result && getSppasToolsIp()
        .equals(other.getSppasToolsIp());
    result = result && getCacheDirectory()
        .equals(other.getCacheDirectory());
    result = result && (getSpeed()
        == other.getSpeed());
    result = result && (hasReportAccurateVoiceCommandMessage() == other.hasReportAccurateVoiceCommandMessage());
    if (hasReportAccurateVoiceCommandMessage()) {
      result = result && getReportAccurateVoiceCommandMessage()
          .equals(other.getReportAccurateVoiceCommandMessage());
    }
    result = result && (hasReportVoiceRecognizedMessage() == other.hasReportVoiceRecognizedMessage());
    if (hasReportVoiceRecognizedMessage()) {
      result = result && getReportVoiceRecognizedMessage()
          .equals(other.getReportVoiceRecognizedMessage());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TTSENGINE_FIELD_NUMBER;
    hash = (53 * hash) + getTtsEngine().hashCode();
    hash = (37 * hash) + TTSENGINEYUEHANTHK_FIELD_NUMBER;
    hash = (53 * hash) + getTtsEngineYueHantHk().hashCode();
    hash = (37 * hash) + TTSENGINEENUS_FIELD_NUMBER;
    hash = (53 * hash) + getTtsEngineEnUs().hashCode();
    hash = (37 * hash) + XIAOINUANCESERVICEURL_FIELD_NUMBER;
    hash = (53 * hash) + getXiaoINuanceServiceUrl().hashCode();
    hash = (37 * hash) + BIAOBEISERVICEURL_FIELD_NUMBER;
    hash = (53 * hash) + getBiaobeiServiceUrl().hashCode();
    hash = (37 * hash) + BIAOBEISERVICEUSERID_FIELD_NUMBER;
    hash = (53 * hash) + getBiaobeiServiceUserId().hashCode();
    hash = (37 * hash) + XUNFEISDKAPPID_FIELD_NUMBER;
    hash = (53 * hash) + getXunfeiSdkAppId().hashCode();
    hash = (37 * hash) + XUNFEISDKLIBMSCSODIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getXunfeiSdkLibMscSoDirectory().hashCode();
    hash = (37 * hash) + SPPASTOOLSIP_FIELD_NUMBER;
    hash = (53 * hash) + getSppasToolsIp().hashCode();
    hash = (37 * hash) + CACHEDIRECTORY_FIELD_NUMBER;
    hash = (53 * hash) + getCacheDirectory().hashCode();
    hash = (37 * hash) + SPEED_FIELD_NUMBER;
    hash = (53 * hash) + getSpeed();
    if (hasReportAccurateVoiceCommandMessage()) {
      hash = (37 * hash) + REPORTACCURATEVOICECOMMANDMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getReportAccurateVoiceCommandMessage().hashCode();
    }
    if (hasReportVoiceRecognizedMessage()) {
      hash = (37 * hash) + REPORTVOICERECOGNIZEDMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getReportVoiceRecognizedMessage().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)
      com.stupidbeauty.hxlauncher.SpeakerSubSystemMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.SpeakerSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_SpeakerSubSystemMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.SpeakerSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_SpeakerSubSystemMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.class, com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      ttsEngine_ = "";

      ttsEngineYueHantHk_ = "";

      ttsEngineEnUs_ = "";

      xiaoINuanceServiceUrl_ = "";

      biaobeiServiceUrl_ = "";

      biaobeiServiceUserId_ = "";

      xunfeiSdkAppId_ = "";

      xunfeiSdkLibMscSoDirectory_ = "";

      sppasToolsIp_ = "";

      cacheDirectory_ = "";

      speed_ = 0;

      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        reportAccurateVoiceCommandMessage_ = null;
      } else {
        reportAccurateVoiceCommandMessage_ = null;
        reportAccurateVoiceCommandMessageBuilder_ = null;
      }
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        reportVoiceRecognizedMessage_ = null;
      } else {
        reportVoiceRecognizedMessage_ = null;
        reportVoiceRecognizedMessageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.SpeakerSubSystemMessageProtos.internal_static_com_stupidbeauty_hxlauncher_SpeakerSubSystemMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage build() {
      com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage buildPartial() {
      com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage result = new com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage(this);
      result.ttsEngine_ = ttsEngine_;
      result.ttsEngineYueHantHk_ = ttsEngineYueHantHk_;
      result.ttsEngineEnUs_ = ttsEngineEnUs_;
      result.xiaoINuanceServiceUrl_ = xiaoINuanceServiceUrl_;
      result.biaobeiServiceUrl_ = biaobeiServiceUrl_;
      result.biaobeiServiceUserId_ = biaobeiServiceUserId_;
      result.xunfeiSdkAppId_ = xunfeiSdkAppId_;
      result.xunfeiSdkLibMscSoDirectory_ = xunfeiSdkLibMscSoDirectory_;
      result.sppasToolsIp_ = sppasToolsIp_;
      result.cacheDirectory_ = cacheDirectory_;
      result.speed_ = speed_;
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        result.reportAccurateVoiceCommandMessage_ = reportAccurateVoiceCommandMessage_;
      } else {
        result.reportAccurateVoiceCommandMessage_ = reportAccurateVoiceCommandMessageBuilder_.build();
      }
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        result.reportVoiceRecognizedMessage_ = reportVoiceRecognizedMessage_;
      } else {
        result.reportVoiceRecognizedMessage_ = reportVoiceRecognizedMessageBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage) {
        return mergeFrom((com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage other) {
      if (other == com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage.getDefaultInstance()) return this;
      if (!other.getTtsEngine().isEmpty()) {
        ttsEngine_ = other.ttsEngine_;
        onChanged();
      }
      if (!other.getTtsEngineYueHantHk().isEmpty()) {
        ttsEngineYueHantHk_ = other.ttsEngineYueHantHk_;
        onChanged();
      }
      if (!other.getTtsEngineEnUs().isEmpty()) {
        ttsEngineEnUs_ = other.ttsEngineEnUs_;
        onChanged();
      }
      if (!other.getXiaoINuanceServiceUrl().isEmpty()) {
        xiaoINuanceServiceUrl_ = other.xiaoINuanceServiceUrl_;
        onChanged();
      }
      if (!other.getBiaobeiServiceUrl().isEmpty()) {
        biaobeiServiceUrl_ = other.biaobeiServiceUrl_;
        onChanged();
      }
      if (!other.getBiaobeiServiceUserId().isEmpty()) {
        biaobeiServiceUserId_ = other.biaobeiServiceUserId_;
        onChanged();
      }
      if (!other.getXunfeiSdkAppId().isEmpty()) {
        xunfeiSdkAppId_ = other.xunfeiSdkAppId_;
        onChanged();
      }
      if (!other.getXunfeiSdkLibMscSoDirectory().isEmpty()) {
        xunfeiSdkLibMscSoDirectory_ = other.xunfeiSdkLibMscSoDirectory_;
        onChanged();
      }
      if (!other.getSppasToolsIp().isEmpty()) {
        sppasToolsIp_ = other.sppasToolsIp_;
        onChanged();
      }
      if (!other.getCacheDirectory().isEmpty()) {
        cacheDirectory_ = other.cacheDirectory_;
        onChanged();
      }
      if (other.getSpeed() != 0) {
        setSpeed(other.getSpeed());
      }
      if (other.hasReportAccurateVoiceCommandMessage()) {
        mergeReportAccurateVoiceCommandMessage(other.getReportAccurateVoiceCommandMessage());
      }
      if (other.hasReportVoiceRecognizedMessage()) {
        mergeReportVoiceRecognizedMessage(other.getReportVoiceRecognizedMessage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object ttsEngine_ = "";
    /**
     * <pre>
     *简体中文的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngine = 1;</code>
     */
    public java.lang.String getTtsEngine() {
      java.lang.Object ref = ttsEngine_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ttsEngine_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *简体中文的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngine = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTtsEngineBytes() {
      java.lang.Object ref = ttsEngine_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ttsEngine_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *简体中文的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngine = 1;</code>
     */
    public Builder setTtsEngine(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ttsEngine_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *简体中文的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngine = 1;</code>
     */
    public Builder clearTtsEngine() {
      
      ttsEngine_ = getDefaultInstance().getTtsEngine();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *简体中文的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngine = 1;</code>
     */
    public Builder setTtsEngineBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ttsEngine_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ttsEngineYueHantHk_ = "";
    /**
     * <pre>
     *广东话的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineYueHantHk = 2;</code>
     */
    public java.lang.String getTtsEngineYueHantHk() {
      java.lang.Object ref = ttsEngineYueHantHk_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ttsEngineYueHantHk_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *广东话的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineYueHantHk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTtsEngineYueHantHkBytes() {
      java.lang.Object ref = ttsEngineYueHantHk_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ttsEngineYueHantHk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *广东话的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineYueHantHk = 2;</code>
     */
    public Builder setTtsEngineYueHantHk(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ttsEngineYueHantHk_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广东话的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineYueHantHk = 2;</code>
     */
    public Builder clearTtsEngineYueHantHk() {
      
      ttsEngineYueHantHk_ = getDefaultInstance().getTtsEngineYueHantHk();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *广东话的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineYueHantHk = 2;</code>
     */
    public Builder setTtsEngineYueHantHkBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ttsEngineYueHantHk_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ttsEngineEnUs_ = "";
    /**
     * <pre>
     *英语的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineEnUs = 3;</code>
     */
    public java.lang.String getTtsEngineEnUs() {
      java.lang.Object ref = ttsEngineEnUs_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ttsEngineEnUs_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *英语的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineEnUs = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTtsEngineEnUsBytes() {
      java.lang.Object ref = ttsEngineEnUs_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ttsEngineEnUs_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *英语的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineEnUs = 3;</code>
     */
    public Builder setTtsEngineEnUs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ttsEngineEnUs_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英语的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineEnUs = 3;</code>
     */
    public Builder clearTtsEngineEnUs() {
      
      ttsEngineEnUs_ = getDefaultInstance().getTtsEngineEnUs();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *英语的语音合成引擎。
     * </pre>
     *
     * <code>string ttsEngineEnUs = 3;</code>
     */
    public Builder setTtsEngineEnUsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ttsEngineEnUs_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object xiaoINuanceServiceUrl_ = "";
    /**
     * <pre>
     *Nuance语音合成的引擎地址。
     * </pre>
     *
     * <code>string xiaoINuanceServiceUrl = 4;</code>
     */
    public java.lang.String getXiaoINuanceServiceUrl() {
      java.lang.Object ref = xiaoINuanceServiceUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        xiaoINuanceServiceUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *Nuance语音合成的引擎地址。
     * </pre>
     *
     * <code>string xiaoINuanceServiceUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getXiaoINuanceServiceUrlBytes() {
      java.lang.Object ref = xiaoINuanceServiceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xiaoINuanceServiceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *Nuance语音合成的引擎地址。
     * </pre>
     *
     * <code>string xiaoINuanceServiceUrl = 4;</code>
     */
    public Builder setXiaoINuanceServiceUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      xiaoINuanceServiceUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Nuance语音合成的引擎地址。
     * </pre>
     *
     * <code>string xiaoINuanceServiceUrl = 4;</code>
     */
    public Builder clearXiaoINuanceServiceUrl() {
      
      xiaoINuanceServiceUrl_ = getDefaultInstance().getXiaoINuanceServiceUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *Nuance语音合成的引擎地址。
     * </pre>
     *
     * <code>string xiaoINuanceServiceUrl = 4;</code>
     */
    public Builder setXiaoINuanceServiceUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      xiaoINuanceServiceUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object biaobeiServiceUrl_ = "";
    /**
     * <pre>
     *标贝语音合成的服务地址。
     * </pre>
     *
     * <code>string biaobeiServiceUrl = 5;</code>
     */
    public java.lang.String getBiaobeiServiceUrl() {
      java.lang.Object ref = biaobeiServiceUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        biaobeiServiceUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *标贝语音合成的服务地址。
     * </pre>
     *
     * <code>string biaobeiServiceUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getBiaobeiServiceUrlBytes() {
      java.lang.Object ref = biaobeiServiceUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        biaobeiServiceUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *标贝语音合成的服务地址。
     * </pre>
     *
     * <code>string biaobeiServiceUrl = 5;</code>
     */
    public Builder setBiaobeiServiceUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      biaobeiServiceUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标贝语音合成的服务地址。
     * </pre>
     *
     * <code>string biaobeiServiceUrl = 5;</code>
     */
    public Builder clearBiaobeiServiceUrl() {
      
      biaobeiServiceUrl_ = getDefaultInstance().getBiaobeiServiceUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标贝语音合成的服务地址。
     * </pre>
     *
     * <code>string biaobeiServiceUrl = 5;</code>
     */
    public Builder setBiaobeiServiceUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      biaobeiServiceUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object biaobeiServiceUserId_ = "";
    /**
     * <pre>
     *标贝语音合成的用户编号。
     * </pre>
     *
     * <code>string biaobeiServiceUserId = 6;</code>
     */
    public java.lang.String getBiaobeiServiceUserId() {
      java.lang.Object ref = biaobeiServiceUserId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        biaobeiServiceUserId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *标贝语音合成的用户编号。
     * </pre>
     *
     * <code>string biaobeiServiceUserId = 6;</code>
     */
    public com.google.protobuf.ByteString
        getBiaobeiServiceUserIdBytes() {
      java.lang.Object ref = biaobeiServiceUserId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        biaobeiServiceUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *标贝语音合成的用户编号。
     * </pre>
     *
     * <code>string biaobeiServiceUserId = 6;</code>
     */
    public Builder setBiaobeiServiceUserId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      biaobeiServiceUserId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标贝语音合成的用户编号。
     * </pre>
     *
     * <code>string biaobeiServiceUserId = 6;</code>
     */
    public Builder clearBiaobeiServiceUserId() {
      
      biaobeiServiceUserId_ = getDefaultInstance().getBiaobeiServiceUserId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *标贝语音合成的用户编号。
     * </pre>
     *
     * <code>string biaobeiServiceUserId = 6;</code>
     */
    public Builder setBiaobeiServiceUserIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      biaobeiServiceUserId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object xunfeiSdkAppId_ = "";
    /**
     * <pre>
     *设置三维人像的背景图片。
     * </pre>
     *
     * <code>string xunfeiSdkAppId = 7;</code>
     */
    public java.lang.String getXunfeiSdkAppId() {
      java.lang.Object ref = xunfeiSdkAppId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        xunfeiSdkAppId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *设置三维人像的背景图片。
     * </pre>
     *
     * <code>string xunfeiSdkAppId = 7;</code>
     */
    public com.google.protobuf.ByteString
        getXunfeiSdkAppIdBytes() {
      java.lang.Object ref = xunfeiSdkAppId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xunfeiSdkAppId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *设置三维人像的背景图片。
     * </pre>
     *
     * <code>string xunfeiSdkAppId = 7;</code>
     */
    public Builder setXunfeiSdkAppId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      xunfeiSdkAppId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设置三维人像的背景图片。
     * </pre>
     *
     * <code>string xunfeiSdkAppId = 7;</code>
     */
    public Builder clearXunfeiSdkAppId() {
      
      xunfeiSdkAppId_ = getDefaultInstance().getXunfeiSdkAppId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *设置三维人像的背景图片。
     * </pre>
     *
     * <code>string xunfeiSdkAppId = 7;</code>
     */
    public Builder setXunfeiSdkAppIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      xunfeiSdkAppId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object xunfeiSdkLibMscSoDirectory_ = "";
    /**
     * <pre>
     *讯飞语音合成的SO文件的目录。
     * </pre>
     *
     * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
     */
    public java.lang.String getXunfeiSdkLibMscSoDirectory() {
      java.lang.Object ref = xunfeiSdkLibMscSoDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        xunfeiSdkLibMscSoDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *讯飞语音合成的SO文件的目录。
     * </pre>
     *
     * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
     */
    public com.google.protobuf.ByteString
        getXunfeiSdkLibMscSoDirectoryBytes() {
      java.lang.Object ref = xunfeiSdkLibMscSoDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        xunfeiSdkLibMscSoDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *讯飞语音合成的SO文件的目录。
     * </pre>
     *
     * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
     */
    public Builder setXunfeiSdkLibMscSoDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      xunfeiSdkLibMscSoDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *讯飞语音合成的SO文件的目录。
     * </pre>
     *
     * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
     */
    public Builder clearXunfeiSdkLibMscSoDirectory() {
      
      xunfeiSdkLibMscSoDirectory_ = getDefaultInstance().getXunfeiSdkLibMscSoDirectory();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *讯飞语音合成的SO文件的目录。
     * </pre>
     *
     * <code>string xunfeiSdkLibMscSoDirectory = 8;</code>
     */
    public Builder setXunfeiSdkLibMscSoDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      xunfeiSdkLibMscSoDirectory_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object sppasToolsIp_ = "";
    /**
     * <pre>
     *SPPAS模块的IP。
     * </pre>
     *
     * <code>string sppasToolsIp = 9;</code>
     */
    public java.lang.String getSppasToolsIp() {
      java.lang.Object ref = sppasToolsIp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sppasToolsIp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *SPPAS模块的IP。
     * </pre>
     *
     * <code>string sppasToolsIp = 9;</code>
     */
    public com.google.protobuf.ByteString
        getSppasToolsIpBytes() {
      java.lang.Object ref = sppasToolsIp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sppasToolsIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *SPPAS模块的IP。
     * </pre>
     *
     * <code>string sppasToolsIp = 9;</code>
     */
    public Builder setSppasToolsIp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      sppasToolsIp_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *SPPAS模块的IP。
     * </pre>
     *
     * <code>string sppasToolsIp = 9;</code>
     */
    public Builder clearSppasToolsIp() {
      
      sppasToolsIp_ = getDefaultInstance().getSppasToolsIp();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *SPPAS模块的IP。
     * </pre>
     *
     * <code>string sppasToolsIp = 9;</code>
     */
    public Builder setSppasToolsIpBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      sppasToolsIp_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cacheDirectory_ = "";
    /**
     * <pre>
     *声音缓存文件目录。
     * </pre>
     *
     * <code>string cacheDirectory = 10;</code>
     */
    public java.lang.String getCacheDirectory() {
      java.lang.Object ref = cacheDirectory_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cacheDirectory_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *声音缓存文件目录。
     * </pre>
     *
     * <code>string cacheDirectory = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCacheDirectoryBytes() {
      java.lang.Object ref = cacheDirectory_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cacheDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *声音缓存文件目录。
     * </pre>
     *
     * <code>string cacheDirectory = 10;</code>
     */
    public Builder setCacheDirectory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cacheDirectory_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *声音缓存文件目录。
     * </pre>
     *
     * <code>string cacheDirectory = 10;</code>
     */
    public Builder clearCacheDirectory() {
      
      cacheDirectory_ = getDefaultInstance().getCacheDirectory();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *声音缓存文件目录。
     * </pre>
     *
     * <code>string cacheDirectory = 10;</code>
     */
    public Builder setCacheDirectoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cacheDirectory_ = value;
      onChanged();
      return this;
    }

    private int speed_ ;
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 speed = 11;</code>
     */
    public int getSpeed() {
      return speed_;
    }
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 speed = 11;</code>
     */
    public Builder setSpeed(int value) {
      
      speed_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语速。
     * </pre>
     *
     * <code>int32 speed = 11;</code>
     */
    public Builder clearSpeed() {
      
      speed_ = 0;
      onChanged();
      return this;
    }

    private com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq, com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.Builder, com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder> reportAccurateVoiceCommandMessageBuilder_;
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public boolean hasReportAccurateVoiceCommandMessage() {
      return reportAccurateVoiceCommandMessageBuilder_ != null || reportAccurateVoiceCommandMessage_ != null;
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq getReportAccurateVoiceCommandMessage() {
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        return reportAccurateVoiceCommandMessage_ == null ? com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.getDefaultInstance() : reportAccurateVoiceCommandMessage_;
      } else {
        return reportAccurateVoiceCommandMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public Builder setReportAccurateVoiceCommandMessage(com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq value) {
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reportAccurateVoiceCommandMessage_ = value;
        onChanged();
      } else {
        reportAccurateVoiceCommandMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public Builder setReportAccurateVoiceCommandMessage(
        com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.Builder builderForValue) {
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        reportAccurateVoiceCommandMessage_ = builderForValue.build();
        onChanged();
      } else {
        reportAccurateVoiceCommandMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public Builder mergeReportAccurateVoiceCommandMessage(com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq value) {
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        if (reportAccurateVoiceCommandMessage_ != null) {
          reportAccurateVoiceCommandMessage_ =
            com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.newBuilder(reportAccurateVoiceCommandMessage_).mergeFrom(value).buildPartial();
        } else {
          reportAccurateVoiceCommandMessage_ = value;
        }
        onChanged();
      } else {
        reportAccurateVoiceCommandMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public Builder clearReportAccurateVoiceCommandMessage() {
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        reportAccurateVoiceCommandMessage_ = null;
        onChanged();
      } else {
        reportAccurateVoiceCommandMessage_ = null;
        reportAccurateVoiceCommandMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.Builder getReportAccurateVoiceCommandMessageBuilder() {
      
      onChanged();
      return getReportAccurateVoiceCommandMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    public com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder getReportAccurateVoiceCommandMessageOrBuilder() {
      if (reportAccurateVoiceCommandMessageBuilder_ != null) {
        return reportAccurateVoiceCommandMessageBuilder_.getMessageOrBuilder();
      } else {
        return reportAccurateVoiceCommandMessage_ == null ?
            com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.getDefaultInstance() : reportAccurateVoiceCommandMessage_;
      }
    }
    /**
     * <pre>
     *报告精确语音指令。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq reportAccurateVoiceCommandMessage = 19;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq, com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.Builder, com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder> 
        getReportAccurateVoiceCommandMessageFieldBuilder() {
      if (reportAccurateVoiceCommandMessageBuilder_ == null) {
        reportAccurateVoiceCommandMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq, com.stupidbeauty.hxlauncher.AccurateVoiceCommandReq.Builder, com.stupidbeauty.hxlauncher.AccurateVoiceCommandReqOrBuilder>(
                getReportAccurateVoiceCommandMessage(),
                getParentForChildren(),
                isClean());
        reportAccurateVoiceCommandMessage_ = null;
      }
      return reportAccurateVoiceCommandMessageBuilder_;
    }

    private com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq, com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.Builder, com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder> reportVoiceRecognizedMessageBuilder_;
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public boolean hasReportVoiceRecognizedMessage() {
      return reportVoiceRecognizedMessageBuilder_ != null || reportVoiceRecognizedMessage_ != null;
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq getReportVoiceRecognizedMessage() {
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        return reportVoiceRecognizedMessage_ == null ? com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.getDefaultInstance() : reportVoiceRecognizedMessage_;
      } else {
        return reportVoiceRecognizedMessageBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public Builder setReportVoiceRecognizedMessage(com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq value) {
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        reportVoiceRecognizedMessage_ = value;
        onChanged();
      } else {
        reportVoiceRecognizedMessageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public Builder setReportVoiceRecognizedMessage(
        com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.Builder builderForValue) {
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        reportVoiceRecognizedMessage_ = builderForValue.build();
        onChanged();
      } else {
        reportVoiceRecognizedMessageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public Builder mergeReportVoiceRecognizedMessage(com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq value) {
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        if (reportVoiceRecognizedMessage_ != null) {
          reportVoiceRecognizedMessage_ =
            com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.newBuilder(reportVoiceRecognizedMessage_).mergeFrom(value).buildPartial();
        } else {
          reportVoiceRecognizedMessage_ = value;
        }
        onChanged();
      } else {
        reportVoiceRecognizedMessageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public Builder clearReportVoiceRecognizedMessage() {
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        reportVoiceRecognizedMessage_ = null;
        onChanged();
      } else {
        reportVoiceRecognizedMessage_ = null;
        reportVoiceRecognizedMessageBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.Builder getReportVoiceRecognizedMessageBuilder() {
      
      onChanged();
      return getReportVoiceRecognizedMessageFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    public com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder getReportVoiceRecognizedMessageOrBuilder() {
      if (reportVoiceRecognizedMessageBuilder_ != null) {
        return reportVoiceRecognizedMessageBuilder_.getMessageOrBuilder();
      } else {
        return reportVoiceRecognizedMessage_ == null ?
            com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.getDefaultInstance() : reportVoiceRecognizedMessage_;
      }
    }
    /**
     * <pre>
     *报告语音识别结果。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq reportVoiceRecognizedMessage = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq, com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.Builder, com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder> 
        getReportVoiceRecognizedMessageFieldBuilder() {
      if (reportVoiceRecognizedMessageBuilder_ == null) {
        reportVoiceRecognizedMessageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq, com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReq.Builder, com.stupidbeauty.hxlauncher.ReportVoiceRecognizedReqOrBuilder>(
                getReportVoiceRecognizedMessage(),
                getParentForChildren(),
                isClean());
        reportVoiceRecognizedMessage_ = null;
      }
      return reportVoiceRecognizedMessageBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage)
  private static final com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage();
  }

  public static com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SpeakerSubSystemMessage>
      PARSER = new com.google.protobuf.AbstractParser<SpeakerSubSystemMessage>() {
    @java.lang.Override
    public SpeakerSubSystemMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SpeakerSubSystemMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SpeakerSubSystemMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SpeakerSubSystemMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.SpeakerSubSystemMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

