// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TTSEngineOptionMessage.proto

package com.stupidbeauty.hxlauncher;

/**
 * Protobuf type {@code com.stupidbeauty.hxlauncher.TTSEngineOptionMessage}
 */
public  final class TTSEngineOptionMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.stupidbeauty.hxlauncher.TTSEngineOptionMessage)
    TTSEngineOptionMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use TTSEngineOptionMessage.newBuilder() to construct.
  private TTSEngineOptionMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TTSEngineOptionMessage() {
    engineCode_ = "";
    languageCode_ = "";
    voiceNameOrURL_ = "";
    languageDesc_ = "";
    engineDesc_ = "";
    desc_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private TTSEngineOptionMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            engineCode_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            languageCode_ = s;
            break;
          }
          case 26: {
            com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder subBuilder = null;
            if (engineParameter_ != null) {
              subBuilder = engineParameter_.toBuilder();
            }
            engineParameter_ = input.readMessage(com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(engineParameter_);
              engineParameter_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            voiceNameOrURL_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            languageDesc_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            engineDesc_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            desc_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.stupidbeauty.hxlauncher.TTSEngineOptionMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineOptionMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.stupidbeauty.hxlauncher.TTSEngineOptionMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineOptionMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.class, com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.Builder.class);
  }

  public static final int ENGINECODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object engineCode_;
  /**
   * <pre>
   *引擎代码。
   * </pre>
   *
   * <code>string engineCode = 1;</code>
   */
  public java.lang.String getEngineCode() {
    java.lang.Object ref = engineCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *引擎代码。
   * </pre>
   *
   * <code>string engineCode = 1;</code>
   */
  public com.google.protobuf.ByteString
      getEngineCodeBytes() {
    java.lang.Object ref = engineCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGECODE_FIELD_NUMBER = 2;
  private volatile java.lang.Object languageCode_;
  /**
   * <pre>
   *语言代码。
   * </pre>
   *
   * <code>string languageCode = 2;</code>
   */
  public java.lang.String getLanguageCode() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageCode_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *语言代码。
   * </pre>
   *
   * <code>string languageCode = 2;</code>
   */
  public com.google.protobuf.ByteString
      getLanguageCodeBytes() {
    java.lang.Object ref = languageCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENGINEPARAMETER_FIELD_NUMBER = 3;
  private com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter_;
  /**
   * <pre>
   *具体引擎的参数。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
   */
  public boolean hasEngineParameter() {
    return engineParameter_ != null;
  }
  /**
   * <pre>
   *具体引擎的参数。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
   */
  public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage getEngineParameter() {
    return engineParameter_ == null ? com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.getDefaultInstance() : engineParameter_;
  }
  /**
   * <pre>
   *具体引擎的参数。
   * </pre>
   *
   * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
   */
  public com.stupidbeauty.hxlauncher.TTSEngineParameterMessageOrBuilder getEngineParameterOrBuilder() {
    return getEngineParameter();
  }

  public static final int VOICENAMEORURL_FIELD_NUMBER = 4;
  private volatile java.lang.Object voiceNameOrURL_;
  /**
   * <pre>
   *声音名字或网址。
   * </pre>
   *
   * <code>string voiceNameOrURL = 4;</code>
   */
  public java.lang.String getVoiceNameOrURL() {
    java.lang.Object ref = voiceNameOrURL_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      voiceNameOrURL_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *声音名字或网址。
   * </pre>
   *
   * <code>string voiceNameOrURL = 4;</code>
   */
  public com.google.protobuf.ByteString
      getVoiceNameOrURLBytes() {
    java.lang.Object ref = voiceNameOrURL_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      voiceNameOrURL_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGEDESC_FIELD_NUMBER = 5;
  private volatile java.lang.Object languageDesc_;
  /**
   * <pre>
   *语言描述。
   * </pre>
   *
   * <code>string languageDesc = 5;</code>
   */
  public java.lang.String getLanguageDesc() {
    java.lang.Object ref = languageDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      languageDesc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *语言描述。
   * </pre>
   *
   * <code>string languageDesc = 5;</code>
   */
  public com.google.protobuf.ByteString
      getLanguageDescBytes() {
    java.lang.Object ref = languageDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      languageDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ENGINEDESC_FIELD_NUMBER = 6;
  private volatile java.lang.Object engineDesc_;
  /**
   * <pre>
   *引擎描述。
   * </pre>
   *
   * <code>string engineDesc = 6;</code>
   */
  public java.lang.String getEngineDesc() {
    java.lang.Object ref = engineDesc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      engineDesc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *引擎描述。
   * </pre>
   *
   * <code>string engineDesc = 6;</code>
   */
  public com.google.protobuf.ByteString
      getEngineDescBytes() {
    java.lang.Object ref = engineDesc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      engineDesc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 7;
  private volatile java.lang.Object desc_;
  /**
   * <pre>
   *描述。
   * </pre>
   *
   * <code>string desc = 7;</code>
   */
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *描述。
   * </pre>
   *
   * <code>string desc = 7;</code>
   */
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getEngineCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, engineCode_);
    }
    if (!getLanguageCodeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, languageCode_);
    }
    if (engineParameter_ != null) {
      output.writeMessage(3, getEngineParameter());
    }
    if (!getVoiceNameOrURLBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, voiceNameOrURL_);
    }
    if (!getLanguageDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, languageDesc_);
    }
    if (!getEngineDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, engineDesc_);
    }
    if (!getDescBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, desc_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getEngineCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, engineCode_);
    }
    if (!getLanguageCodeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, languageCode_);
    }
    if (engineParameter_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getEngineParameter());
    }
    if (!getVoiceNameOrURLBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, voiceNameOrURL_);
    }
    if (!getLanguageDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, languageDesc_);
    }
    if (!getEngineDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, engineDesc_);
    }
    if (!getDescBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, desc_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.stupidbeauty.hxlauncher.TTSEngineOptionMessage)) {
      return super.equals(obj);
    }
    com.stupidbeauty.hxlauncher.TTSEngineOptionMessage other = (com.stupidbeauty.hxlauncher.TTSEngineOptionMessage) obj;

    boolean result = true;
    result = result && getEngineCode()
        .equals(other.getEngineCode());
    result = result && getLanguageCode()
        .equals(other.getLanguageCode());
    result = result && (hasEngineParameter() == other.hasEngineParameter());
    if (hasEngineParameter()) {
      result = result && getEngineParameter()
          .equals(other.getEngineParameter());
    }
    result = result && getVoiceNameOrURL()
        .equals(other.getVoiceNameOrURL());
    result = result && getLanguageDesc()
        .equals(other.getLanguageDesc());
    result = result && getEngineDesc()
        .equals(other.getEngineDesc());
    result = result && getDesc()
        .equals(other.getDesc());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ENGINECODE_FIELD_NUMBER;
    hash = (53 * hash) + getEngineCode().hashCode();
    hash = (37 * hash) + LANGUAGECODE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageCode().hashCode();
    if (hasEngineParameter()) {
      hash = (37 * hash) + ENGINEPARAMETER_FIELD_NUMBER;
      hash = (53 * hash) + getEngineParameter().hashCode();
    }
    hash = (37 * hash) + VOICENAMEORURL_FIELD_NUMBER;
    hash = (53 * hash) + getVoiceNameOrURL().hashCode();
    hash = (37 * hash) + LANGUAGEDESC_FIELD_NUMBER;
    hash = (53 * hash) + getLanguageDesc().hashCode();
    hash = (37 * hash) + ENGINEDESC_FIELD_NUMBER;
    hash = (53 * hash) + getEngineDesc().hashCode();
    hash = (37 * hash) + DESC_FIELD_NUMBER;
    hash = (53 * hash) + getDesc().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.stupidbeauty.hxlauncher.TTSEngineOptionMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.stupidbeauty.hxlauncher.TTSEngineOptionMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.stupidbeauty.hxlauncher.TTSEngineOptionMessage)
      com.stupidbeauty.hxlauncher.TTSEngineOptionMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.stupidbeauty.hxlauncher.TTSEngineOptionMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineOptionMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.stupidbeauty.hxlauncher.TTSEngineOptionMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineOptionMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.class, com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.Builder.class);
    }

    // Construct using com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      engineCode_ = "";

      languageCode_ = "";

      if (engineParameterBuilder_ == null) {
        engineParameter_ = null;
      } else {
        engineParameter_ = null;
        engineParameterBuilder_ = null;
      }
      voiceNameOrURL_ = "";

      languageDesc_ = "";

      engineDesc_ = "";

      desc_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.stupidbeauty.hxlauncher.TTSEngineOptionMessageProtos.internal_static_com_stupidbeauty_hxlauncher_TTSEngineOptionMessage_descriptor;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.TTSEngineOptionMessage getDefaultInstanceForType() {
      return com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.TTSEngineOptionMessage build() {
      com.stupidbeauty.hxlauncher.TTSEngineOptionMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.stupidbeauty.hxlauncher.TTSEngineOptionMessage buildPartial() {
      com.stupidbeauty.hxlauncher.TTSEngineOptionMessage result = new com.stupidbeauty.hxlauncher.TTSEngineOptionMessage(this);
      result.engineCode_ = engineCode_;
      result.languageCode_ = languageCode_;
      if (engineParameterBuilder_ == null) {
        result.engineParameter_ = engineParameter_;
      } else {
        result.engineParameter_ = engineParameterBuilder_.build();
      }
      result.voiceNameOrURL_ = voiceNameOrURL_;
      result.languageDesc_ = languageDesc_;
      result.engineDesc_ = engineDesc_;
      result.desc_ = desc_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.stupidbeauty.hxlauncher.TTSEngineOptionMessage) {
        return mergeFrom((com.stupidbeauty.hxlauncher.TTSEngineOptionMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.stupidbeauty.hxlauncher.TTSEngineOptionMessage other) {
      if (other == com.stupidbeauty.hxlauncher.TTSEngineOptionMessage.getDefaultInstance()) return this;
      if (!other.getEngineCode().isEmpty()) {
        engineCode_ = other.engineCode_;
        onChanged();
      }
      if (!other.getLanguageCode().isEmpty()) {
        languageCode_ = other.languageCode_;
        onChanged();
      }
      if (other.hasEngineParameter()) {
        mergeEngineParameter(other.getEngineParameter());
      }
      if (!other.getVoiceNameOrURL().isEmpty()) {
        voiceNameOrURL_ = other.voiceNameOrURL_;
        onChanged();
      }
      if (!other.getLanguageDesc().isEmpty()) {
        languageDesc_ = other.languageDesc_;
        onChanged();
      }
      if (!other.getEngineDesc().isEmpty()) {
        engineDesc_ = other.engineDesc_;
        onChanged();
      }
      if (!other.getDesc().isEmpty()) {
        desc_ = other.desc_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.stupidbeauty.hxlauncher.TTSEngineOptionMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.stupidbeauty.hxlauncher.TTSEngineOptionMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object engineCode_ = "";
    /**
     * <pre>
     *引擎代码。
     * </pre>
     *
     * <code>string engineCode = 1;</code>
     */
    public java.lang.String getEngineCode() {
      java.lang.Object ref = engineCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *引擎代码。
     * </pre>
     *
     * <code>string engineCode = 1;</code>
     */
    public com.google.protobuf.ByteString
        getEngineCodeBytes() {
      java.lang.Object ref = engineCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *引擎代码。
     * </pre>
     *
     * <code>string engineCode = 1;</code>
     */
    public Builder setEngineCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      engineCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *引擎代码。
     * </pre>
     *
     * <code>string engineCode = 1;</code>
     */
    public Builder clearEngineCode() {
      
      engineCode_ = getDefaultInstance().getEngineCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *引擎代码。
     * </pre>
     *
     * <code>string engineCode = 1;</code>
     */
    public Builder setEngineCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      engineCode_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object languageCode_ = "";
    /**
     * <pre>
     *语言代码。
     * </pre>
     *
     * <code>string languageCode = 2;</code>
     */
    public java.lang.String getLanguageCode() {
      java.lang.Object ref = languageCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *语言代码。
     * </pre>
     *
     * <code>string languageCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageCodeBytes() {
      java.lang.Object ref = languageCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *语言代码。
     * </pre>
     *
     * <code>string languageCode = 2;</code>
     */
    public Builder setLanguageCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      languageCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语言代码。
     * </pre>
     *
     * <code>string languageCode = 2;</code>
     */
    public Builder clearLanguageCode() {
      
      languageCode_ = getDefaultInstance().getLanguageCode();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语言代码。
     * </pre>
     *
     * <code>string languageCode = 2;</code>
     */
    public Builder setLanguageCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      languageCode_ = value;
      onChanged();
      return this;
    }

    private com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.TTSEngineParameterMessage, com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder, com.stupidbeauty.hxlauncher.TTSEngineParameterMessageOrBuilder> engineParameterBuilder_;
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public boolean hasEngineParameter() {
      return engineParameterBuilder_ != null || engineParameter_ != null;
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage getEngineParameter() {
      if (engineParameterBuilder_ == null) {
        return engineParameter_ == null ? com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.getDefaultInstance() : engineParameter_;
      } else {
        return engineParameterBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public Builder setEngineParameter(com.stupidbeauty.hxlauncher.TTSEngineParameterMessage value) {
      if (engineParameterBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        engineParameter_ = value;
        onChanged();
      } else {
        engineParameterBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public Builder setEngineParameter(
        com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder builderForValue) {
      if (engineParameterBuilder_ == null) {
        engineParameter_ = builderForValue.build();
        onChanged();
      } else {
        engineParameterBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public Builder mergeEngineParameter(com.stupidbeauty.hxlauncher.TTSEngineParameterMessage value) {
      if (engineParameterBuilder_ == null) {
        if (engineParameter_ != null) {
          engineParameter_ =
            com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.newBuilder(engineParameter_).mergeFrom(value).buildPartial();
        } else {
          engineParameter_ = value;
        }
        onChanged();
      } else {
        engineParameterBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public Builder clearEngineParameter() {
      if (engineParameterBuilder_ == null) {
        engineParameter_ = null;
        onChanged();
      } else {
        engineParameter_ = null;
        engineParameterBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder getEngineParameterBuilder() {
      
      onChanged();
      return getEngineParameterFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    public com.stupidbeauty.hxlauncher.TTSEngineParameterMessageOrBuilder getEngineParameterOrBuilder() {
      if (engineParameterBuilder_ != null) {
        return engineParameterBuilder_.getMessageOrBuilder();
      } else {
        return engineParameter_ == null ?
            com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.getDefaultInstance() : engineParameter_;
      }
    }
    /**
     * <pre>
     *具体引擎的参数。
     * </pre>
     *
     * <code>.com.stupidbeauty.hxlauncher.TTSEngineParameterMessage engineParameter = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.stupidbeauty.hxlauncher.TTSEngineParameterMessage, com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder, com.stupidbeauty.hxlauncher.TTSEngineParameterMessageOrBuilder> 
        getEngineParameterFieldBuilder() {
      if (engineParameterBuilder_ == null) {
        engineParameterBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.stupidbeauty.hxlauncher.TTSEngineParameterMessage, com.stupidbeauty.hxlauncher.TTSEngineParameterMessage.Builder, com.stupidbeauty.hxlauncher.TTSEngineParameterMessageOrBuilder>(
                getEngineParameter(),
                getParentForChildren(),
                isClean());
        engineParameter_ = null;
      }
      return engineParameterBuilder_;
    }

    private java.lang.Object voiceNameOrURL_ = "";
    /**
     * <pre>
     *声音名字或网址。
     * </pre>
     *
     * <code>string voiceNameOrURL = 4;</code>
     */
    public java.lang.String getVoiceNameOrURL() {
      java.lang.Object ref = voiceNameOrURL_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        voiceNameOrURL_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *声音名字或网址。
     * </pre>
     *
     * <code>string voiceNameOrURL = 4;</code>
     */
    public com.google.protobuf.ByteString
        getVoiceNameOrURLBytes() {
      java.lang.Object ref = voiceNameOrURL_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        voiceNameOrURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *声音名字或网址。
     * </pre>
     *
     * <code>string voiceNameOrURL = 4;</code>
     */
    public Builder setVoiceNameOrURL(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      voiceNameOrURL_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *声音名字或网址。
     * </pre>
     *
     * <code>string voiceNameOrURL = 4;</code>
     */
    public Builder clearVoiceNameOrURL() {
      
      voiceNameOrURL_ = getDefaultInstance().getVoiceNameOrURL();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *声音名字或网址。
     * </pre>
     *
     * <code>string voiceNameOrURL = 4;</code>
     */
    public Builder setVoiceNameOrURLBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      voiceNameOrURL_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object languageDesc_ = "";
    /**
     * <pre>
     *语言描述。
     * </pre>
     *
     * <code>string languageDesc = 5;</code>
     */
    public java.lang.String getLanguageDesc() {
      java.lang.Object ref = languageDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        languageDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *语言描述。
     * </pre>
     *
     * <code>string languageDesc = 5;</code>
     */
    public com.google.protobuf.ByteString
        getLanguageDescBytes() {
      java.lang.Object ref = languageDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        languageDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *语言描述。
     * </pre>
     *
     * <code>string languageDesc = 5;</code>
     */
    public Builder setLanguageDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      languageDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语言描述。
     * </pre>
     *
     * <code>string languageDesc = 5;</code>
     */
    public Builder clearLanguageDesc() {
      
      languageDesc_ = getDefaultInstance().getLanguageDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *语言描述。
     * </pre>
     *
     * <code>string languageDesc = 5;</code>
     */
    public Builder setLanguageDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      languageDesc_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object engineDesc_ = "";
    /**
     * <pre>
     *引擎描述。
     * </pre>
     *
     * <code>string engineDesc = 6;</code>
     */
    public java.lang.String getEngineDesc() {
      java.lang.Object ref = engineDesc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        engineDesc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *引擎描述。
     * </pre>
     *
     * <code>string engineDesc = 6;</code>
     */
    public com.google.protobuf.ByteString
        getEngineDescBytes() {
      java.lang.Object ref = engineDesc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        engineDesc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *引擎描述。
     * </pre>
     *
     * <code>string engineDesc = 6;</code>
     */
    public Builder setEngineDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      engineDesc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *引擎描述。
     * </pre>
     *
     * <code>string engineDesc = 6;</code>
     */
    public Builder clearEngineDesc() {
      
      engineDesc_ = getDefaultInstance().getEngineDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *引擎描述。
     * </pre>
     *
     * <code>string engineDesc = 6;</code>
     */
    public Builder setEngineDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      engineDesc_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <pre>
     *描述。
     * </pre>
     *
     * <code>string desc = 7;</code>
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *描述。
     * </pre>
     *
     * <code>string desc = 7;</code>
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *描述。
     * </pre>
     *
     * <code>string desc = 7;</code>
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      desc_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *描述。
     * </pre>
     *
     * <code>string desc = 7;</code>
     */
    public Builder clearDesc() {
      
      desc_ = getDefaultInstance().getDesc();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *描述。
     * </pre>
     *
     * <code>string desc = 7;</code>
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      desc_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.stupidbeauty.hxlauncher.TTSEngineOptionMessage)
  }

  // @@protoc_insertion_point(class_scope:com.stupidbeauty.hxlauncher.TTSEngineOptionMessage)
  private static final com.stupidbeauty.hxlauncher.TTSEngineOptionMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.stupidbeauty.hxlauncher.TTSEngineOptionMessage();
  }

  public static com.stupidbeauty.hxlauncher.TTSEngineOptionMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TTSEngineOptionMessage>
      PARSER = new com.google.protobuf.AbstractParser<TTSEngineOptionMessage>() {
    @java.lang.Override
    public TTSEngineOptionMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new TTSEngineOptionMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TTSEngineOptionMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TTSEngineOptionMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.stupidbeauty.hxlauncher.TTSEngineOptionMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

